/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentSourceMetadata } from './paymentSourceMetadata';
import { PaymentSourceType } from './paymentSourceType';

/**
* Payment done via supported Spotnana payment types.
*/
export class ActualPayment {
    /**
    * Type of payment source.
    */
    'paymentSourceType': PaymentSourceType;
    /**
    * Type of payment source.
    */
    'paymentMetadata': PaymentSourceMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentSourceType",
            "baseName": "paymentSourceType",
            "type": "PaymentSourceType"
        },
        {
            "name": "paymentMetadata",
            "baseName": "paymentMetadata",
            "type": "PaymentSourceMetadata"
        }    ];

    static getAttributeTypeMap() {
        return ActualPayment.attributeTypeMap;
    }
}

export namespace ActualPayment {
}
