/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThirdPartyPnrRemark } from './thirdPartyPnrRemark';

/**
* Response on adding remark.
*/
export class AddRemarksResponse {
    /**
    * The list of remarks added to the given PNR.
    */
    'processedRemarks'?: Array<ThirdPartyPnrRemark>;
    /**
    * The list of remarks ignored.
    */
    'ignoredRemarks'?: Array<ThirdPartyPnrRemark>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "processedRemarks",
            "baseName": "processedRemarks",
            "type": "Array<ThirdPartyPnrRemark>"
        },
        {
            "name": "ignoredRemarks",
            "baseName": "ignoredRemarks",
            "type": "Array<ThirdPartyPnrRemark>"
        }    ];

    static getAttributeTypeMap() {
        return AddRemarksResponse.attributeTypeMap;
    }
}

