/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileOwner } from './profileOwner';

/**
* Basic information related to ad-hoc traveler profile.
*/
export class AdhocUserInfo {
    'profileOwner': ProfileOwner;
    /**
    * A boolean flag to show if ad-hoc traveler is visible in search. While updating the user  if client tries to update this field, it will throw exception. 
    */
    'isSaved'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "profileOwner",
            "baseName": "profileOwner",
            "type": "ProfileOwner"
        },
        {
            "name": "isSaved",
            "baseName": "isSaved",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AdhocUserInfo.attributeTypeMap;
    }
}

