/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirportInfo } from './airportInfo';
import { EventBookingWindow } from './eventBookingWindow';

/**
* Air related guidelines
*/
export class AirBookingGuideline {
    /**
    * List of allowed airports for arrival of flight-in-event and departure of flight-out-event.
    */
    'allowedAirports'?: Array<AirportInfo>;
    /**
    * Booking window for flight-in-event.
    */
    'arrivalBookingWindow': EventBookingWindow;
    /**
    * Booking window for flight-out-event.
    */
    'departureBookingWindow': EventBookingWindow;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedAirports",
            "baseName": "allowedAirports",
            "type": "Array<AirportInfo>"
        },
        {
            "name": "arrivalBookingWindow",
            "baseName": "arrivalBookingWindow",
            "type": "EventBookingWindow"
        },
        {
            "name": "departureBookingWindow",
            "baseName": "departureBookingWindow",
            "type": "EventBookingWindow"
        }    ];

    static getAttributeTypeMap() {
        return AirBookingGuideline.attributeTypeMap;
    }
}

