/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirBookingGuideline } from './airBookingGuideline';

/**
* Wrapper for AirBookingGuideline
*/
export class AirBookingGuidelineWrapper {
    'airBookingGuideLine'?: AirBookingGuideline;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airBookingGuideLine",
            "baseName": "airBookingGuideLine",
            "type": "AirBookingGuideline"
        }    ];

    static getAttributeTypeMap() {
        return AirBookingGuidelineWrapper.attributeTypeMap;
    }
}

