/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* - CANCELLABLE_BY_OBT: Cancellation possible via API. - CANCELLABLE_BY_SUPPORT: Cancellation possible via agent support. - NON_CANCELLABLE: Booking is non-cancellable. - CANCELLATION_IN_PROGRESS: Cancellation is in progress. - CANCELLATION_BY_AGENT_REQUESTED: Cancellation request has been sent to agent. - CANCELLED: Already cancelled. - CANCELLATION_INFO_NOT_AVAILABLE: Cancellation information not available. 
*/
export enum AirCancellationState {
    CancellableByObt = <any> 'CANCELLABLE_BY_OBT',
    CancellableBySupport = <any> 'CANCELLABLE_BY_SUPPORT',
    NonCancellable = <any> 'NON_CANCELLABLE',
    CancellationInProgress = <any> 'CANCELLATION_IN_PROGRESS',
    CancellationByAgentRequested = <any> 'CANCELLATION_BY_AGENT_REQUESTED',
    Cancelled = <any> 'CANCELLED',
    CancellationInfoNotAvailable = <any> 'CANCELLATION_INFO_NOT_AVAILABLE'
}
