/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Airline preferences.
*/
export class AirlinePref {
    'airlines'?: Array<string>;
    'flightType'?: AirlinePref.FlightTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airlines",
            "baseName": "airlines",
            "type": "Array<string>"
        },
        {
            "name": "flightType",
            "baseName": "flightType",
            "type": "AirlinePref.FlightTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return AirlinePref.attributeTypeMap;
    }
}

export namespace AirlinePref {
    export enum FlightTypeEnum {
        UnknownFlightType = <any> 'UNKNOWN_FLIGHT_TYPE',
        Domestic = <any> 'DOMESTIC',
        International = <any> 'INTERNATIONAL',
        All = <any> 'ALL'
    }
}
