/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Airline } from './airline';
import { AirlineProgramMetadata } from './airlineProgramMetadata';

/**
* Descriptor for Airline program details.
*/
export class AirlineProgram {
    /**
    * Eligible airlines\' information list.
    */
    'airlineInfo': Array<Airline>;
    /**
    * Airline program payment specific metadata.
    */
    'airlineProgramMetadata': AirlineProgramMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airlineInfo",
            "baseName": "airlineInfo",
            "type": "Array<Airline>"
        },
        {
            "name": "airlineProgramMetadata",
            "baseName": "airlineProgramMetadata",
            "type": "AirlineProgramMetadata"
        }    ];

    static getAttributeTypeMap() {
        return AirlineProgram.attributeTypeMap;
    }
}

