/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Airline Details
*/
export class Airline {
    /**
    * Unique code for the Airline
    */
    'carrierCode': string;
    /**
    * Full Name of the Airline
    */
    'airlineName': string;
    /**
    * Whether the airline is present in preferred vendor list. This is an optional field which gets populated only in the preferred vendor autocomplete API.
    */
    'isPresentInPreferredVendors'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carrierCode",
            "baseName": "carrierCode",
            "type": "string"
        },
        {
            "name": "airlineName",
            "baseName": "airlineName",
            "type": "string"
        },
        {
            "name": "isPresentInPreferredVendors",
            "baseName": "isPresentInPreferredVendors",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Airline.attributeTypeMap;
    }
}

