/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UAPassPlusMetadata } from './uAPassPlusMetadata';
import { UAPassPlusMetadataWrapper } from './uAPassPlusMetadataWrapper';
import { UATPMetadata } from './uATPMetadata';
import { UATPMetadataWrapper } from './uATPMetadataWrapper';

export class AirlineProgramMetadata {
    'uatpMetadata'?: UATPMetadata;
    'uaPassPlusMetadata'?: UAPassPlusMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uatpMetadata",
            "baseName": "uatpMetadata",
            "type": "UATPMetadata"
        },
        {
            "name": "uaPassPlusMetadata",
            "baseName": "uaPassPlusMetadata",
            "type": "UAPassPlusMetadata"
        }    ];

    static getAttributeTypeMap() {
        return AirlineProgramMetadata.attributeTypeMap;
    }
}

