/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';

/**
* Information related to air price optimization if PNR has been rebooked. 
*/
export class AirPriceOptimizationMetadata {
    /**
    * List of old tickets present in PNR before rebook. For non-ticketed PNRs, tickets will not be present. 
    */
    'oldTickets'?: Array<string>;
    /**
    * List of new tickets in PNR after rebook. For non-ticketed PNRs, tickets will not be present. 
    */
    'newTickets'?: Array<string>;
    /**
    * Old Spotnana PnrId of the PNR before rebook. 
    */
    'oldPnrId': string;
    /**
    * New Spotnana PnrId of the PNR after rebook. If the same PNR has been modified during rebook, oldPnrId and newPnrId will be same. If a new PNR has been booked during rebook, oldPnrId and newPnrId will be different. 
    */
    'newPnrId': string;
    /**
    * Total price of the PNR before rebook.
    */
    'oldPrice': Money;
    /**
    * Total price of the PNR after rebook.
    */
    'newPrice': Money;
    /**
    * Total price drop during rebook process.
    */
    'priceDrop': Money;
    /**
    * Penalty amount paid during rebook process.
    */
    'penaltyPrice'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "oldTickets",
            "baseName": "oldTickets",
            "type": "Array<string>"
        },
        {
            "name": "newTickets",
            "baseName": "newTickets",
            "type": "Array<string>"
        },
        {
            "name": "oldPnrId",
            "baseName": "oldPnrId",
            "type": "string"
        },
        {
            "name": "newPnrId",
            "baseName": "newPnrId",
            "type": "string"
        },
        {
            "name": "oldPrice",
            "baseName": "oldPrice",
            "type": "Money"
        },
        {
            "name": "newPrice",
            "baseName": "newPrice",
            "type": "Money"
        },
        {
            "name": "priceDrop",
            "baseName": "priceDrop",
            "type": "Money"
        },
        {
            "name": "penaltyPrice",
            "baseName": "penaltyPrice",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return AirPriceOptimizationMetadata.attributeTypeMap;
    }
}

