/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirlinePref } from './airlinePref';
import { AlliancePref } from './alliancePref';
import { FarePref } from './farePref';
import { MealPref } from './mealPref';
import { NumStopsPref } from './numStopsPref';
import { PreferredAirport } from './preferredAirport';
import { SeatAmenityPref } from './seatAmenityPref';
import { SeatLocationPref } from './seatLocationPref';

/**
* Travel preferences related to air travel.
*/
export class AirPref {
    'airlinePrefs'?: Array<AirlinePref>;
    'alliancePref'?: AlliancePref;
    'farePref'?: FarePref;
    'homeAirport'?: string;
    'mealPref'?: MealPref;
    'numStopPref'?: NumStopsPref;
    'seatAmenityPref'?: SeatAmenityPref;
    'seatLocationPrefs'?: Array<SeatLocationPref>;
    /**
    * A list of user preferred airports.
    */
    'preferredAirports'?: Array<PreferredAirport>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airlinePrefs",
            "baseName": "airlinePrefs",
            "type": "Array<AirlinePref>"
        },
        {
            "name": "alliancePref",
            "baseName": "alliancePref",
            "type": "AlliancePref"
        },
        {
            "name": "farePref",
            "baseName": "farePref",
            "type": "FarePref"
        },
        {
            "name": "homeAirport",
            "baseName": "homeAirport",
            "type": "string"
        },
        {
            "name": "mealPref",
            "baseName": "mealPref",
            "type": "MealPref"
        },
        {
            "name": "numStopPref",
            "baseName": "numStopPref",
            "type": "NumStopsPref"
        },
        {
            "name": "seatAmenityPref",
            "baseName": "seatAmenityPref",
            "type": "SeatAmenityPref"
        },
        {
            "name": "seatLocationPrefs",
            "baseName": "seatLocationPrefs",
            "type": "Array<SeatLocationPref>"
        },
        {
            "name": "preferredAirports",
            "baseName": "preferredAirports",
            "type": "Array<PreferredAirport>"
        }    ];

    static getAttributeTypeMap() {
        return AirPref.attributeTypeMap;
    }
}

