/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirPriceOptimizationMetadata } from './airPriceOptimizationMetadata';

/**
* Wrapper for AirPriceOptimizationMetadata.
*/
export class AirPriceOptimizationMetadataWrapper {
    'airPriceOptimizationMetadata'?: AirPriceOptimizationMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airPriceOptimizationMetadata",
            "baseName": "airPriceOptimizationMetadata",
            "type": "AirPriceOptimizationMetadata"
        }    ];

    static getAttributeTypeMap() {
        return AirPriceOptimizationMetadataWrapper.attributeTypeMap;
    }
}

