/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirCancellationOption } from './airCancellationOption';
import { TicketCancellationInfo } from './ticketCancellationInfo';
import { UserId } from './userId';

/**
* Cancellation information for traveler.
*/
export class AirTravelerCancellationInfo {
    /**
    * User ID of traveler.
    */
    'userId': UserId;
    /**
    * Cancellation information for traveler tickets.
    */
    'tickets': Array<TicketCancellationInfo>;
    /**
    * Cancellation options for this traveler.
    */
    'cancellationOptions'?: Array<AirCancellationOption>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "tickets",
            "baseName": "tickets",
            "type": "Array<TicketCancellationInfo>"
        },
        {
            "name": "cancellationOptions",
            "baseName": "cancellationOptions",
            "type": "Array<AirCancellationOption>"
        }    ];

    static getAttributeTypeMap() {
        return AirTravelerCancellationInfo.attributeTypeMap;
    }
}

