/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum Alliance {
    UnknownAlliance = <any> 'UNKNOWN_ALLIANCE',
    StarAlliance = <any> 'STAR_ALLIANCE',
    Oneworld = <any> 'ONEWORLD',
    Skyteam = <any> 'SKYTEAM',
    VanillaAlliance = <any> 'VANILLA_ALLIANCE',
    UFlyAlliance = <any> 'U_FLY_ALLIANCE',
    ValueAlliance = <any> 'VALUE_ALLIANCE'
}
