/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FareAmount } from './fareAmount';
import { Money } from './money';

/**
* Information about credit redeemed in booking.
*/
export class AppliedCreditInfo {
    /**
    * Unique ID of credit applied. For example, numeric ID of unused ticket.
    */
    'creditId': string;
    /**
    * Total credit amount available.
    */
    'creditAmount'?: FareAmount;
    /**
    * Difference between the selected fare and credit available. If the fare is greater than credit available, value of this field will be positive (that amount will be charged to payment method). If the fare is less than credit available, value of this field will be negative (credit balance will remain). 
    */
    'fareDifference'?: Money;
    /**
    * Penalty amount applied to redeem credit. This could be a change fee applied when redeeming.
    */
    'penalty'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creditId",
            "baseName": "creditId",
            "type": "string"
        },
        {
            "name": "creditAmount",
            "baseName": "creditAmount",
            "type": "FareAmount"
        },
        {
            "name": "fareDifference",
            "baseName": "fareDifference",
            "type": "Money"
        },
        {
            "name": "penalty",
            "baseName": "penalty",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return AppliedCreditInfo.attributeTypeMap;
    }
}

