/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApprovalInfo {
    /**
    * The approval status for the PNR
    */
    'approvalStatus': ApprovalInfo.ApprovalStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "approvalStatus",
            "baseName": "approvalStatus",
            "type": "ApprovalInfo.ApprovalStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ApprovalInfo.attributeTypeMap;
    }
}

export namespace ApprovalInfo {
    export enum ApprovalStatusEnum {
        ApprovalPending = <any> 'APPROVAL_PENDING',
        Approved = <any> 'APPROVED',
        Denied = <any> 'DENIED',
        TimedOut = <any> 'TIMED_OUT',
        TimedOutReminder = <any> 'TIMED_OUT_REMINDER',
        ApprovalNotRequired = <any> 'APPROVAL_NOT_REQUIRED',
        SoftApprovalTimeout = <any> 'SOFT_APPROVAL_TIMEOUT'
    }
}
