/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancellationInfo } from './cancellationInfo';

/**
* Info related to possible automated cancellations
*/
export class AutomatedCancellationInfo {
    /**
    * Supported automated cancellations. If this list is empty, automated cancellation is not  supported for this booking 
    */
    'supportedCancellations'?: Array<CancellationInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "supportedCancellations",
            "baseName": "supportedCancellations",
            "type": "Array<CancellationInfo>"
        }    ];

    static getAttributeTypeMap() {
        return AutomatedCancellationInfo.attributeTypeMap;
    }
}

