/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BagPolicyApplicability } from './bagPolicyApplicability';
import { Money } from './money';

/**
* This contains price info for the baggage
*/
export class BagFees {
    'fee'?: Money;
    'applicability'?: BagPolicyApplicability;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fee",
            "baseName": "fee",
            "type": "Money"
        },
        {
            "name": "applicability",
            "baseName": "applicability",
            "type": "BagPolicyApplicability"
        }    ];

    static getAttributeTypeMap() {
        return BagFees.attributeTypeMap;
    }
}

export namespace BagFees {
}
