/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BagFees } from './bagFees';
import { BagWeightLimit } from './bagWeightLimit';
import { SizeInfo } from './sizeInfo';

/**
* Information about the baggage policy.
*/
export class BaggageInfo {
    /**
    * Baggage policy text
    */
    'description'?: string;
    /**
    * Count of bags
    */
    'count'?: number;
    /**
    * Size of bag in cm
    */
    'sizeLimitInfo'?: Array<SizeInfo>;
    /**
    * Array of bag weight limits
    */
    'weightLimitInfo'?: Array<BagWeightLimit>;
    /**
    * Array of bag weight fees
    */
    'fee'?: Array<BagFees>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "sizeLimitInfo",
            "baseName": "sizeLimitInfo",
            "type": "Array<SizeInfo>"
        },
        {
            "name": "weightLimitInfo",
            "baseName": "weightLimitInfo",
            "type": "Array<BagWeightLimit>"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "Array<BagFees>"
        }    ];

    static getAttributeTypeMap() {
        return BaggageInfo.attributeTypeMap;
    }
}

