/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Bed types.
*/
export enum BedType {
    UnknownBedType = <any> 'UNKNOWN_BED_TYPE',
    Double = <any> 'DOUBLE',
    Futon = <any> 'FUTON',
    King = <any> 'KING',
    Murphy = <any> 'MURPHY',
    Queen = <any> 'QUEEN',
    Sofa = <any> 'SOFA',
    TatamiMats = <any> 'TATAMI_MATS',
    Twin = <any> 'TWIN',
    Single = <any> 'SINGLE',
    Full = <any> 'FULL',
    RunOfTheHouse = <any> 'RUN_OF_THE_HOUSE',
    Dorm = <any> 'DORM',
    Water = <any> 'WATER',
    PullOut = <any> 'PULL_OUT',
    TwinXl = <any> 'TWIN_XL'
}
