/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Boarding pass information for the corresponding flight.
*/
export class BoardingPass {
    /**
    * Index of leg to which this boarding pass belongs.
    */
    'legIndex'?: number;
    /**
    * Index of flight in it\'s leg to which this boarding pass belongs.
    */
    'flightIndex'?: number;
    /**
    * Boarding Priority for airlines like Southwest which have open seating.
    */
    'boardingPriority'?: string;
    /**
    * Boarding zone for airlines like Southwest which have open seating.
    */
    'boardingZone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legIndex",
            "baseName": "legIndex",
            "type": "number"
        },
        {
            "name": "flightIndex",
            "baseName": "flightIndex",
            "type": "number"
        },
        {
            "name": "boardingPriority",
            "baseName": "boardingPriority",
            "type": "string"
        },
        {
            "name": "boardingZone",
            "baseName": "boardingZone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BoardingPass.attributeTypeMap;
    }
}

