/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FareStatistics } from './fareStatistics';

/**
* Metadata like fare statistics for this booking
*/
export class BookingMetadata {
    /**
    * Fare statistics of all logical itineraries. In case of multi pax, only primary i.e.  adult fare is included in stats. 
    */
    'fareStatistics'?: FareStatistics;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fareStatistics",
            "baseName": "fareStatistics",
            "type": "FareStatistics"
        }    ];

    static getAttributeTypeMap() {
        return BookingMetadata.attributeTypeMap;
    }
}

