/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlightSeatStatus } from './flightSeatStatus';
import { Money } from './money';

export class BookingSeatsInner {
    /**
    * Index of leg to which this seat belongs
    */
    'legIdx'?: number;
    /**
    * Index of flight in it\'s leg to which this seat belongs
    */
    'flightIdx'?: number;
    /**
    * Total seat price
    */
    'amount'?: Money;
    /**
    * Assigned seat number
    */
    'number'?: string;
    /**
    * Seat booking status
    */
    'status'?: FlightSeatStatus;
    /**
    * Raw status code of the seat. E.g. HK, KK.
    */
    'sourceStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legIdx",
            "baseName": "legIdx",
            "type": "number"
        },
        {
            "name": "flightIdx",
            "baseName": "flightIdx",
            "type": "number"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "FlightSeatStatus"
        },
        {
            "name": "sourceStatus",
            "baseName": "sourceStatus",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BookingSeatsInner.attributeTypeMap;
    }
}

export namespace BookingSeatsInner {
}
