/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details associated with object to be cancel.
*/
export class CancelObjectDetail {
    /**
    * Type of entity to be cancel.
    */
    'cancelObjectType'?: CancelObjectDetail.CancelObjectTypeEnum;
    /**
    * Unique ID of Cancel Object
    */
    'cancelObjectId'?: string;
    /**
    * Vendor cancellation Id of the supplier.
    */
    'vendorCancellationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelObjectType",
            "baseName": "cancelObjectType",
            "type": "CancelObjectDetail.CancelObjectTypeEnum"
        },
        {
            "name": "cancelObjectId",
            "baseName": "cancelObjectId",
            "type": "string"
        },
        {
            "name": "vendorCancellationId",
            "baseName": "vendorCancellationId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CancelObjectDetail.attributeTypeMap;
    }
}

export namespace CancelObjectDetail {
    export enum CancelObjectTypeEnum {
        Pnr = <any> 'PNR',
        Ticket = <any> 'TICKET',
        Journey = <any> 'JOURNEY'
    }
}
