/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelObjectDetail } from './cancelObjectDetail';
import { RefundInfoDetail } from './refundInfoDetail';

/**
* Describe the details associated with cancel PNR.
*/
export class CancelDetail {
    'cancelObjectDetail'?: CancelObjectDetail;
    /**
    * List of refund details associated with the cancel object.
    */
    'refundInfo'?: Array<RefundInfoDetail>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelObjectDetail",
            "baseName": "cancelObjectDetail",
            "type": "CancelObjectDetail"
        },
        {
            "name": "refundInfo",
            "baseName": "refundInfo",
            "type": "Array<RefundInfoDetail>"
        }    ];

    static getAttributeTypeMap() {
        return CancelDetail.attributeTypeMap;
    }
}

