/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Status of in progress cancellation request CANCELLATION_IN_PROGRESS - Cancellation request is in progress via OBT CANCELLATION_BY_AGENT_REQUESTED - Cancellation request is in progress via agent 
*/
export enum CancellationRequestStatus {
    InProgress = <any> 'CANCELLATION_IN_PROGRESS',
    ByAgentRequested = <any> 'CANCELLATION_BY_AGENT_REQUESTED'
}
