/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Expiry } from './expiry';
import { ExpiryWrapper } from './expiryWrapper';
import { TokenizedExpiry } from './tokenizedExpiry';
import { TokenizedExpiryWrapper } from './tokenizedExpiryWrapper';

/**
* Contains the expiry of a Card.
*/
export class CardExpiry {
    'tokenizedExpiry'?: TokenizedExpiry;
    'expiry'?: Expiry;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tokenizedExpiry",
            "baseName": "tokenizedExpiry",
            "type": "TokenizedExpiry"
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "Expiry"
        }    ];

    static getAttributeTypeMap() {
        return CardExpiry.attributeTypeMap;
    }
}

