/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Card } from './card';
import { CreditCardAccess } from './creditCardAccess';

/**
* Metadata for Card payment source.
*/
export class CardMetadata2 {
    'card'?: Card;
    'accessType'?: CreditCardAccess;
    /**
    * Whether the payment is made using a lodge card
    */
    'isLodgeCard'?: boolean;
    /**
    * Whether this is a BTA card. Possible values are \'Y\' or \'N\'. Relevant only for lodge cards.
    */
    'bta'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "card",
            "baseName": "card",
            "type": "Card"
        },
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "CreditCardAccess"
        },
        {
            "name": "isLodgeCard",
            "baseName": "isLodgeCard",
            "type": "boolean"
        },
        {
            "name": "bta",
            "baseName": "bta",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CardMetadata2.attributeTypeMap;
    }
}

