/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The issuing company of card
*/
export enum CardCompany {
    None = <any> 'NONE',
    Visa = <any> 'VISA',
    Mastercard = <any> 'MASTERCARD',
    Amex = <any> 'AMEX',
    Discover = <any> 'DISCOVER',
    AirTravelUatp = <any> 'AIR_TRAVEL_UATP',
    CarteBlanche = <any> 'CARTE_BLANCHE',
    DinersClub = <any> 'DINERS_CLUB',
    Jcb = <any> 'JCB',
    Brex = <any> 'BREX',
    UnionPay = <any> 'UNION_PAY',
    EuroCard = <any> 'EURO_CARD',
    AccessCard = <any> 'ACCESS_CARD'
}
