/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CentralCardAccessLevel } from './centralCardAccessLevel';

/**
* Contains the central access level and entity id.
*/
export class CardAccessEntity {
    /**
    * Holds the id for for the user who can access the card or organization id or legal entity
    */
    'entityId': string;
    'centralCardAccessLevel': CentralCardAccessLevel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string"
        },
        {
            "name": "centralCardAccessLevel",
            "baseName": "centralCardAccessLevel",
            "type": "CentralCardAccessLevel"
        }    ];

    static getAttributeTypeMap() {
        return CardAccessEntity.attributeTypeMap;
    }
}

export namespace CardAccessEntity {
}
