/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CarCo2EmissionDetail } from './carCo2EmissionDetail';
import { CarLocation } from './carLocation';
import { CarSpec } from './carSpec';
import { Length } from './length';
import { Money } from './money';
import { Preference } from './preference';
import { PreferredType } from './preferredType';
import { Vendor } from './vendor';

/**
* Car info
*/
export class CarInfo {
    /**
    * Vehicle information.
    */
    'carSpec': CarSpec;
    /**
    * Drop off location.
    */
    'dropOffLocation': CarLocation;
    /**
    * Mileage allowance.
    */
    'mileageAllowance'?: Length;
    /**
    * Pick up location.
    */
    'pickupLocation': CarLocation;
    'vendor': Vendor;
    /**
    * Car type code
    */
    'carTypeCode'?: string;
    'extraMileageCharge'?: Money;
    /**
    * Car preference
    */
    'preferredType'?: Array<PreferredType>;
    /**
    * Car preferences
    */
    'preferences'?: Array<Preference>;
    /**
    * The CO2 emission detail for car.
    */
    'co2EmissionDetail'?: CarCo2EmissionDetail;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carSpec",
            "baseName": "carSpec",
            "type": "CarSpec"
        },
        {
            "name": "dropOffLocation",
            "baseName": "dropOffLocation",
            "type": "CarLocation"
        },
        {
            "name": "mileageAllowance",
            "baseName": "mileageAllowance",
            "type": "Length"
        },
        {
            "name": "pickupLocation",
            "baseName": "pickupLocation",
            "type": "CarLocation"
        },
        {
            "name": "vendor",
            "baseName": "vendor",
            "type": "Vendor"
        },
        {
            "name": "carTypeCode",
            "baseName": "carTypeCode",
            "type": "string"
        },
        {
            "name": "extraMileageCharge",
            "baseName": "extraMileageCharge",
            "type": "Money"
        },
        {
            "name": "preferredType",
            "baseName": "preferredType",
            "type": "Array<PreferredType>"
        },
        {
            "name": "preferences",
            "baseName": "preferences",
            "type": "Array<Preference>"
        },
        {
            "name": "co2EmissionDetail",
            "baseName": "co2EmissionDetail",
            "type": "CarCo2EmissionDetail"
        }    ];

    static getAttributeTypeMap() {
        return CarInfo.attributeTypeMap;
    }
}

