/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Car type.
*/
export enum CarType {
    Other = <any> 'OTHER',
    Mini = <any> 'MINI',
    Economy = <any> 'ECONOMY',
    Compact = <any> 'COMPACT',
    MidSize = <any> 'MID_SIZE',
    Standard = <any> 'STANDARD',
    FullSize = <any> 'FULL_SIZE',
    Premium = <any> 'PREMIUM',
    Luxury = <any> 'LUXURY',
    Convertible = <any> 'CONVERTIBLE',
    Minivan = <any> 'MINIVAN',
    Suv = <any> 'SUV',
    Van = <any> 'VAN',
    Pickup = <any> 'PICKUP',
    Sports = <any> 'SPORTS',
    Special = <any> 'SPECIAL',
    RecreationalVehicle = <any> 'RECREATIONAL_VEHICLE',
    Wagon = <any> 'WAGON'
}
