/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* CO2 emission info for rail
*/
export class Co2EmissionDetails {
    /**
    * CO2 emission for the outward/inward leg in kilograms for a single passenger.
    */
    'co2EmissionKilograms': number;
    /**
    * Indicates whether the emissions value is approximate or not.
    */
    'isApproximate'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "co2EmissionKilograms",
            "baseName": "co2EmissionKilograms",
            "type": "number"
        },
        {
            "name": "isApproximate",
            "baseName": "isApproximate",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Co2EmissionDetails.attributeTypeMap;
    }
}

