/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* CO2 emission details for the flight.
*/
export class CO2EmissionDetail {
    /**
    * Estimated C02 emissions value for selected flight and seating class, per passenger (in tons)
    */
    'emissionValue': number;
    /**
    * Average estimated C02 emissions per passenger for same route (in tons)
    */
    'averageEmissionValue'?: number;
    /**
    * Total distance flown by the flight in kilometres.
    */
    'flightDistanceKm'?: number;
    /**
    * Indicates whether the emissions value is approximate or not.
    */
    'isApproximate'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emissionValue",
            "baseName": "emissionValue",
            "type": "number"
        },
        {
            "name": "averageEmissionValue",
            "baseName": "averageEmissionValue",
            "type": "number"
        },
        {
            "name": "flightDistanceKm",
            "baseName": "flightDistanceKm",
            "type": "number"
        },
        {
            "name": "isApproximate",
            "baseName": "isApproximate",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CO2EmissionDetail.attributeTypeMap;
    }
}

