/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CompanyId } from './companyId';
import { Image } from './image';

/**
* Basic information about a company.
*/
export class CompanyRef {
    'id': CompanyId;
    'name'?: string;
    /**
    * Company logo
    */
    'logo'?: Image;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "CompanyId"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "Image"
        }    ];

    static getAttributeTypeMap() {
        return CompanyRef.attributeTypeMap;
    }
}

