/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details of conferma - one of virtual card vendors.
*/
export class ConfermaInfo {
    /**
    * Unique identifier assigned to the virtual card deployment at the point of creation.
    */
    'deploymentId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deploymentId",
            "baseName": "deploymentId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ConfermaInfo.attributeTypeMap;
    }
}

