/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Duration } from './duration';

/**
* Alert for connection risk in a leg
*/
export class ConnectionRiskAlert {
    /**
    * Index of departing flight for this connection
    */
    'departingFlightIndex'?: number;
    /**
    * Minimum connection time
    */
    'minConnectionDuration'?: Duration;
    /**
    * Connection time before this alert
    */
    'previousConnectionDuration'?: Duration;
    /**
    * Updated connection time
    */
    'updatedConnectionDuration'?: Duration;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "departingFlightIndex",
            "baseName": "departingFlightIndex",
            "type": "number"
        },
        {
            "name": "minConnectionDuration",
            "baseName": "minConnectionDuration",
            "type": "Duration"
        },
        {
            "name": "previousConnectionDuration",
            "baseName": "previousConnectionDuration",
            "type": "Duration"
        },
        {
            "name": "updatedConnectionDuration",
            "baseName": "updatedConnectionDuration",
            "type": "Duration"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionRiskAlert.attributeTypeMap;
    }
}

