/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CostCenterId } from './costCenterId';

/**
* Cost center details.
*/
export class CostCenter {
    /**
    * Count of employees in the cost center
    */
    'employeeCount'?: number;
    'id': CostCenterId;
    'name': string;
    'externalId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employeeCount",
            "baseName": "employeeCount",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "CostCenterId"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "externalId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CostCenter.attributeTypeMap;
    }
}

