/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CostCommission } from './costCommission';
import { CostExtrasInner } from './costExtrasInner';
import { CostRefundInfo } from './costRefundInfo';
import { CostTaxBreakdown } from './costTaxBreakdown';
import { DateModel } from './dateModel';
import { Money } from './money';

/**
* Rate info for non-air pnr.
*/
export class Cost {
    /**
    * Base Amount.
    */
    'base': Money;
    /**
    * List of extras.
    */
    'extras'?: Array<CostExtrasInner>;
    /**
    * Refund Amount.
    */
    'refund'?: Money;
    /**
    * Tax amount.
    */
    'tax': Money;
    'commission'?: CostCommission;
    'taxBreakdown'?: CostTaxBreakdown;
    /**
    * Transaction date
    */
    'transactionDate'?: DateModel;
    'refundInfo'?: CostRefundInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "base",
            "baseName": "base",
            "type": "Money"
        },
        {
            "name": "extras",
            "baseName": "extras",
            "type": "Array<CostExtrasInner>"
        },
        {
            "name": "refund",
            "baseName": "refund",
            "type": "Money"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "Money"
        },
        {
            "name": "commission",
            "baseName": "commission",
            "type": "CostCommission"
        },
        {
            "name": "taxBreakdown",
            "baseName": "taxBreakdown",
            "type": "CostTaxBreakdown"
        },
        {
            "name": "transactionDate",
            "baseName": "transactionDate",
            "type": "DateModel"
        },
        {
            "name": "refundInfo",
            "baseName": "refundInfo",
            "type": "CostRefundInfo"
        }    ];

    static getAttributeTypeMap() {
        return Cost.attributeTypeMap;
    }
}

