/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Rental car counter location.
*/
export enum CounterLocation {
    UnknownCounter = <any> 'UNKNOWN_COUNTER',
    NonAirportLocation = <any> 'NON_AIRPORT_LOCATION',
    InTerminal = <any> 'IN_TERMINAL',
    OffAirportRentalShuttle = <any> 'OFF_AIRPORT_RENTAL_SHUTTLE',
    InTerminalRentalShuttle = <any> 'IN_TERMINAL_RENTAL_SHUTTLE',
    OnAirportRentalShuttle = <any> 'ON_AIRPORT_RENTAL_SHUTTLE',
    OnAirportAirportShuttle = <any> 'ON_AIRPORT_AIRPORT_SHUTTLE',
    CallForShuttle = <any> 'CALL_FOR_SHUTTLE',
    TwoShuttlesAirportAndRental = <any> 'TWO_SHUTTLES_AIRPORT_AND_RENTAL'
}
