/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserId } from './userId';

/**
* Request body to create a trip, with either userId or registrarId mandatory.
*/
export class CreateTripRequest {
    /**
    * Name of the trip.
    */
    'tripName': string;
    /**
    * Description of the trip.
    */
    'tripDescription'?: string;
    'userId'?: UserId;
    /**
    * Creator of the Trip.
    */
    'registrarId'?: UserId;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tripName",
            "baseName": "tripName",
            "type": "string"
        },
        {
            "name": "tripDescription",
            "baseName": "tripDescription",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "registrarId",
            "baseName": "registrarId",
            "type": "UserId"
        }    ];

    static getAttributeTypeMap() {
        return CreateTripRequest.attributeTypeMap;
    }
}

