/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardAccessEntity } from './cardAccessEntity';
import { CreditCardAccessType } from './creditCardAccessType';

/**
* Access type for cards to check who in the organization has permission to use it
*/
export class CreditCardAccess {
    'accessType': CreditCardAccessType;
    /**
    * Holds the ids for for all users who can access the card or organization id
    */
    'entityIds': Array<string>;
    /**
    * A list of cardAccessEntity consisting of central card access level if present and entity id.
    */
    'entities'?: Array<CardAccessEntity>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "CreditCardAccessType"
        },
        {
            "name": "entityIds",
            "baseName": "entityIds",
            "type": "Array<string>"
        },
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<CardAccessEntity>"
        }    ];

    static getAttributeTypeMap() {
        return CreditCardAccess.attributeTypeMap;
    }
}

export namespace CreditCardAccess {
}
