/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Status of the credit.
*/
export enum CreditStatus {
    StatusUnknown = <any> 'STATUS_UNKNOWN',
    Open = <any> 'OPEN',
    Used = <any> 'USED'
}
