/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Identifies the different ways the card can be used across an organization
*/
export enum CreditCardAccessType {
    UnknownType = <any> 'UNKNOWN_TYPE',
    Centralised = <any> 'CENTRALISED',
    Individual = <any> 'INDIVIDUAL',
    Personal = <any> 'PERSONAL',
    Tmc = <any> 'TMC',
    Application = <any> 'APPLICATION',
    Itinerary = <any> 'ITINERARY',
    Events = <any> 'EVENTS'
}
