/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AmadeusCheckoutMetadata } from './amadeusCheckoutMetadata';
import { AmadeusCheckoutMetadataWrapper } from './amadeusCheckoutMetadataWrapper';
import { BrexBudgetMetadata } from './brexBudgetMetadata';
import { BrexBudgetMetadataWrapper } from './brexBudgetMetadataWrapper';

/**
* Metadata for Custom Payment Method payment source.
*/
export class CustomPaymentMethodMetadata {
    'brexBudgetMetadata': BrexBudgetMetadata;
    'amadeusCheckoutMetadata': AmadeusCheckoutMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "brexBudgetMetadata",
            "baseName": "brexBudgetMetadata",
            "type": "BrexBudgetMetadata"
        },
        {
            "name": "amadeusCheckoutMetadata",
            "baseName": "amadeusCheckoutMetadata",
            "type": "AmadeusCheckoutMetadata"
        }    ];

    static getAttributeTypeMap() {
        return CustomPaymentMethodMetadata.attributeTypeMap;
    }
}

