/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Parameter to form options for the custom field.
*/
export enum CustomFieldOptionsParam {
    CostCenter = <any> 'COST_CENTER',
    LegalEntity = <any> 'LEGAL_ENTITY',
    Office = <any> 'OFFICE',
    Department = <any> 'DEPARTMENT'
}
