/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateTimeLocal } from './dateTimeLocal';

/**
* Date range within which the virtual card can be charged.
*/
export class DateRange {
    'startDate': DateTimeLocal;
    'endDate': DateTimeLocal;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "DateTimeLocal"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "DateTimeLocal"
        }    ];

    static getAttributeTypeMap() {
        return DateRange.attributeTypeMap;
    }
}

