/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DirectBilling2 } from './directBilling2';

/**
* Wrapper for DirectBilling metadata
*/
export class DirectBillingWrapper2 {
    'directBilling': DirectBilling2;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "directBilling",
            "baseName": "directBilling",
            "type": "DirectBilling2"
        }    ];

    static getAttributeTypeMap() {
        return DirectBillingWrapper2.attributeTypeMap;
    }
}

