/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentMetadata } from './documentMetadata';

/**
* Document details.
*/
export class Document {
    /**
    * S3 location of the document.
    */
    'url': string;
    /**
    * Unique identifier of the document.
    */
    'documentId': string;
    'documentMetadata': DocumentMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "documentMetadata",
            "baseName": "documentMetadata",
            "type": "DocumentMetadata"
        }    ];

    static getAttributeTypeMap() {
        return Document.attributeTypeMap;
    }
}

