/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentType } from './documentType';
import { EntityMetadata } from './entityMetadata';
import { EntityType } from './entityType';

/**
* Metadata related to document.
*/
export class DocumentMetadata {
    'documentType': DocumentType;
    'entityType': EntityType;
    /**
    * Entity Id for the given entity type.
    */
    'entityId': string;
    'entityMetadata': EntityMetadata;
    /**
    * Document name.
    */
    'name': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentType",
            "baseName": "documentType",
            "type": "DocumentType"
        },
        {
            "name": "entityType",
            "baseName": "entityType",
            "type": "EntityType"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string"
        },
        {
            "name": "entityMetadata",
            "baseName": "entityMetadata",
            "type": "EntityMetadata"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DocumentMetadata.attributeTypeMap;
    }
}

export namespace DocumentMetadata {
}
