/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Name } from './name';
import { PhoneNumber } from './phoneNumber';
import { PostalAddress } from './postalAddress';
import { UserOrgId } from './userOrgId';

/**
* Emergency contact information.
*/
export class EmergencyContactInfo {
    'address'?: PostalAddress;
    'designation'?: string;
    'email': string;
    'name'?: Name;
    'phoneNumber'?: PhoneNumber;
    'userOrgId'?: UserOrgId;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "PostalAddress"
        },
        {
            "name": "designation",
            "baseName": "designation",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Name"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "PhoneNumber"
        },
        {
            "name": "userOrgId",
            "baseName": "userOrgId",
            "type": "UserOrgId"
        }    ];

    static getAttributeTypeMap() {
        return EmergencyContactInfo.attributeTypeMap;
    }
}

