/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorResponseErrorMessagesInner } from './errorResponseErrorMessagesInner';

export class ErrorResponse {
    /**
    * Link to debug the error internally.
    */
    'debugIdentifier'?: string;
    'errorMessages'?: Array<ErrorResponseErrorMessagesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "debugIdentifier",
            "baseName": "debugIdentifier",
            "type": "string"
        },
        {
            "name": "errorMessages",
            "baseName": "errorMessages",
            "type": "Array<ErrorResponseErrorMessagesInner>"
        }    ];

    static getAttributeTypeMap() {
        return ErrorResponse.attributeTypeMap;
    }
}

