/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorParameter } from './errorParameter';

export class ErrorResponseErrorMessagesInner {
    /**
    * Error code to identify the specific errors.
    */
    'errorCode'?: string;
    /**
    * Message containing details of error.
    */
    'message'?: string;
    /**
    * Error message parameters.
    */
    'errorParameters'?: Array<ErrorParameter>;
    /**
    * More details about the error.
    */
    'errorDetail'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "errorParameters",
            "baseName": "errorParameters",
            "type": "Array<ErrorParameter>"
        },
        {
            "name": "errorDetail",
            "baseName": "errorDetail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ErrorResponseErrorMessagesInner.attributeTypeMap;
    }
}

