/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* For ELECTRONIC_TICKET, it contains e-ticket file info.
*/
export class ETicketMetadata {
    /**
    * E-ticket file name.
    */
    'description'?: string;
    /**
    * E-ticket data as bytes.
    */
    'eticketData': string;
    /**
    * Type of ticket.
    */
    'type': ETicketMetadata.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "eticketData",
            "baseName": "eticketData",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ETicketMetadata.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ETicketMetadata.attributeTypeMap;
    }
}

export namespace ETicketMetadata {
    export enum TypeEnum {
        UnknownType = <any> 'UNKNOWN_TYPE',
        Pdf = <any> 'PDF',
        ApplePkPass = <any> 'APPLE_PK_PASS',
        Html = <any> 'HTML',
        CollectionNumber = <any> 'COLLECTION_NUMBER'
    }
}
