/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Name } from './name';
import { UserId } from './userId';

/**
* User information for the event
*/
export class EventUserInfo {
    'userId': UserId;
    /**
    * Business email of the user
    */
    'email'?: string;
    'name': Name;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Name"
        }    ];

    static getAttributeTypeMap() {
        return EventUserInfo.attributeTypeMap;
    }
}

