/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirRsvpResponse } from './airRsvpResponse';
import { CarRsvpResponse } from './carRsvpResponse';
import { HotelRsvpResponse } from './hotelRsvpResponse';
import { RailRsvpResponse } from './railRsvpResponse';

/**
* Event rsvp response
*/
export class EventRsvpResponse {
    'air'?: AirRsvpResponse;
    'hotel'?: HotelRsvpResponse;
    'car'?: CarRsvpResponse;
    'rail'?: RailRsvpResponse;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "air",
            "baseName": "air",
            "type": "AirRsvpResponse"
        },
        {
            "name": "hotel",
            "baseName": "hotel",
            "type": "HotelRsvpResponse"
        },
        {
            "name": "car",
            "baseName": "car",
            "type": "CarRsvpResponse"
        },
        {
            "name": "rail",
            "baseName": "rail",
            "type": "RailRsvpResponse"
        }    ];

    static getAttributeTypeMap() {
        return EventRsvpResponse.attributeTypeMap;
    }
}

