/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Allowed booking type for the event
*/
export enum EventAllowedBookingType {
    Air = <any> 'AIR',
    Hotel = <any> 'HOTEL',
    Car = <any> 'CAR',
    Rail = <any> 'RAIL'
}
