/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Latlng } from './latlng';
import { PostalAddress } from './postalAddress';

/**
* Location for an event
*/
export class EventLocation {
    'address'?: PostalAddress;
    'coordinates'?: Latlng;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "PostalAddress"
        },
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "Latlng"
        }    ];

    static getAttributeTypeMap() {
        return EventLocation.attributeTypeMap;
    }
}

