/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostalAddress } from './postalAddress';

/**
* Metadata when document is associated to an event.
*/
export class EventEntityMetadata {
    'address'?: PostalAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "PostalAddress"
        }    ];

    static getAttributeTypeMap() {
        return EventEntityMetadata.attributeTypeMap;
    }
}

