/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* In case of exchange, payment accounted to the original ticket.
*/
export class ExchangePayment {
    /**
    * Ticket number which was exchanged to pay for current ticket.
    */
    'originalTicketNumber': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "originalTicketNumber",
            "baseName": "originalTicketNumber",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExchangePayment.attributeTypeMap;
    }
}

