/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LegInfo } from './legInfo';

export class ExchangeInfo {
    /**
    * List of legs supported for this exchange
    */
    'legInfos'?: Array<LegInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legInfos",
            "baseName": "legInfos",
            "type": "Array<LegInfo>"
        }    ];

    static getAttributeTypeMap() {
        return ExchangeInfo.attributeTypeMap;
    }
}

