/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Contains the failure reason in case of any Failed Transaction
*/
export class FailureReason {
    /**
    * Reason Code associated with the Failure
    */
    'reasonCode'?: FailureReason.ReasonCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reasonCode",
            "baseName": "reasonCode",
            "type": "FailureReason.ReasonCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return FailureReason.attributeTypeMap;
    }
}

export namespace FailureReason {
    export enum ReasonCodeEnum {
        MethodMissing = <any> 'PAYMENT_METHOD_MISSING',
        GatewayFailure = <any> 'PAYMENT_GATEWAY_FAILURE'
    }
}
