/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlightId } from './flightId';

/**
* Fare component details for this itinerary
*/
export class FareComponentDetail {
    /**
    * Fare basis code for the booking
    */
    'fareBasisCode': string;
    /**
    * Tour code applied on this fare component
    */
    'tourCode'?: string;
    'flightIds': Array<FlightId>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fareBasisCode",
            "baseName": "fareBasisCode",
            "type": "string"
        },
        {
            "name": "tourCode",
            "baseName": "tourCode",
            "type": "string"
        },
        {
            "name": "flightIds",
            "baseName": "flightIds",
            "type": "Array<FlightId>"
        }    ];

    static getAttributeTypeMap() {
        return FareComponentDetail.attributeTypeMap;
    }
}

