/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaggagePolicy } from './baggagePolicy';
import { CancellationPolicy1 } from './cancellationPolicy1';
import { ExchangePolicy } from './exchangePolicy';
import { UserId } from './userId';

/**
* Fare offers for a traveler
*/
export class FareOffers {
    /**
    * User ID of traveler to which this fare offer applies
    */
    'userId': UserId;
    'baggagePolicy'?: BaggagePolicy;
    'cancellationPolicy'?: CancellationPolicy1;
    'exchangePolicy'?: ExchangePolicy;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "baggagePolicy",
            "baseName": "baggagePolicy",
            "type": "BaggagePolicy"
        },
        {
            "name": "cancellationPolicy",
            "baseName": "cancellationPolicy",
            "type": "CancellationPolicy1"
        },
        {
            "name": "exchangePolicy",
            "baseName": "exchangePolicy",
            "type": "ExchangePolicy"
        }    ];

    static getAttributeTypeMap() {
        return FareOffers.attributeTypeMap;
    }
}

