/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Fare preferences.
*/
export class FarePref {
    'fareTypes': Array<FarePref.FareTypesEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fareTypes",
            "baseName": "fareTypes",
            "type": "Array<FarePref.FareTypesEnum>"
        }    ];

    static getAttributeTypeMap() {
        return FarePref.attributeTypeMap;
    }
}

export namespace FarePref {
    export enum FareTypesEnum {
        UnknownType = <any> 'UNKNOWN_TYPE',
        Changeable = <any> 'CHANGEABLE',
        Refundable = <any> 'REFUNDABLE'
    }
}
