/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FareAmount } from './fareAmount';

export class FlightFareBreakup {
    /**
    * List of legs for this fare info
    */
    'legIndices'?: Array<number>;
    /**
    * Total flight fare for the above legs
    */
    'flightsFare'?: FareAmount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legIndices",
            "baseName": "legIndices",
            "type": "Array<number>"
        },
        {
            "name": "flightsFare",
            "baseName": "flightsFare",
            "type": "FareAmount"
        }    ];

    static getAttributeTypeMap() {
        return FlightFareBreakup.attributeTypeMap;
    }
}

