/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Flight and Leg index details.
*/
export class FlightAndLegIndex {
    /**
    * Flight index within a leg, starts from 0.
    */
    'flightIndex'?: number;
    /**
    * Leg index within a pnr, starts from 0.
    */
    'legIndex'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flightIndex",
            "baseName": "flightIndex",
            "type": "number"
        },
        {
            "name": "legIndex",
            "baseName": "legIndex",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return FlightAndLegIndex.attributeTypeMap;
    }
}

