/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Flight identifier
*/
export class FlightId {
    /**
    * Index of leg to which this flight belongs
    */
    'legIdx': number;
    /**
    * Index of flight in it\'s leg
    */
    'flightIdx': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legIdx",
            "baseName": "legIdx",
            "type": "number"
        },
        {
            "name": "flightIdx",
            "baseName": "flightIdx",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return FlightId.attributeTypeMap;
    }
}

