/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Restrictions like seat booking, loyalty etc.
*/
export enum FlightRestrictions {
    PreBookingSeatNotAllowed = <any> 'PRE_BOOKING_SEAT_NOT_ALLOWED',
    PostBookingSeatNotAllowed = <any> 'POST_BOOKING_SEAT_NOT_ALLOWED',
    SeatBookingNotAllowedDueToBrand = <any> 'SEAT_BOOKING_NOT_ALLOWED_DUE_TO_BRAND',
    SeatBookingNotAllowed = <any> 'SEAT_BOOKING_NOT_ALLOWED',
    SeatBookingNotAllowedOpenSeating = <any> 'SEAT_BOOKING_NOT_ALLOWED_OPEN_SEATING',
    SeatNotGuaranteedWarning = <any> 'SEAT_NOT_GUARANTEED_WARNING',
    SeatBookingNotAllowedDueToCodeshare = <any> 'SEAT_BOOKING_NOT_ALLOWED_DUE_TO_CODESHARE'
}
