/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Flight metadata against which document is associated.
*/
export class FlightMetadata {
    /**
    * Unique identifier of the flight.
    */
    'flightId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flightId",
            "baseName": "flightId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FlightMetadata.attributeTypeMap;
    }
}

