/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateTimeOffset } from './dateTimeOffset';

/**
* Information about the freshness of the data set in this PNR object. This field is only set when the PNR returned is not the latest PNR available. 
*/
export class FreshnessInfo {
    /**
    * Time when the PNR information was updated in Spotnana\'s systems for the latest PNR version available. 
    */
    'latestVersionDateTime': DateTimeOffset;
    /**
    * Time when the PNR information was updated in Spotnana\'s systems for the PNR whose information is in this object. 
    */
    'returnedVersionDateTime': DateTimeOffset;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "latestVersionDateTime",
            "baseName": "latestVersionDateTime",
            "type": "DateTimeOffset"
        },
        {
            "name": "returnedVersionDateTime",
            "baseName": "returnedVersionDateTime",
            "type": "DateTimeOffset"
        }    ];

    static getAttributeTypeMap() {
        return FreshnessInfo.attributeTypeMap;
    }
}

