/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateTimeLocal } from './dateTimeLocal';
import { Duration } from './duration';

export class HiddenStop {
    /**
    * 3 letter IATA airport code
    */
    'airport': string;
    /**
    * Stop start date time
    */
    'arrivalDateTime': DateTimeLocal;
    /**
    * Stop end date time
    */
    'departureDateTime': DateTimeLocal;
    /**
    * Stop duration
    */
    'duration'?: Duration;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airport",
            "baseName": "airport",
            "type": "string"
        },
        {
            "name": "arrivalDateTime",
            "baseName": "arrivalDateTime",
            "type": "DateTimeLocal"
        },
        {
            "name": "departureDateTime",
            "baseName": "departureDateTime",
            "type": "DateTimeLocal"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "Duration"
        }    ];

    static getAttributeTypeMap() {
        return HiddenStop.attributeTypeMap;
    }
}

