/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HotelRoomMealType } from './hotelRoomMealType';
import { HotelRoomMealsIncluded } from './hotelRoomMealsIncluded';

/**
* Meal details for the room.
*/
export class HotelRoomMeal {
    'mealsIncluded'?: Array<HotelRoomMealsIncluded>;
    /**
    * Meal type added with the room booked.
    */
    'mealPlan': HotelRoomMealType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mealsIncluded",
            "baseName": "mealsIncluded",
            "type": "Array<HotelRoomMealsIncluded>"
        },
        {
            "name": "mealPlan",
            "baseName": "mealPlan",
            "type": "HotelRoomMealType"
        }    ];

    static getAttributeTypeMap() {
        return HotelRoomMeal.attributeTypeMap;
    }
}

export namespace HotelRoomMeal {
}
