/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LoyaltyInfo } from './loyaltyInfo';
import { UserId } from './userId';

/**
* Hotel Traveler Info
*/
export class HotelTravelerInfo {
    /**
    * Index of traveler in travelers list to which this info belongs
    */
    'travelerIdx': number;
    /**
    * User ID of traveler to which TravelerInfo belongs
    */
    'userId'?: UserId;
    'loyaltyInfos'?: Array<LoyaltyInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "travelerIdx",
            "baseName": "travelerIdx",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "loyaltyInfos",
            "baseName": "loyaltyInfos",
            "type": "Array<LoyaltyInfo>"
        }    ];

    static getAttributeTypeMap() {
        return HotelTravelerInfo.attributeTypeMap;
    }
}

