/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HotelAmenities } from './hotelAmenities';
import { HotelDescription } from './hotelDescription';
import { HotelImageSet } from './hotelImageSet';
import { Latlng } from './latlng';
import { PhoneNumber } from './phoneNumber';
import { PostalAddress } from './postalAddress';

/**
* Hotel info
*/
export class HotelInfo {
    /**
    * Address of the hotel.
    */
    'address': PostalAddress;
    /**
    * Chain code of the hotel.
    */
    'chainCode'?: string;
    /**
    * Chain name of the hotel.
    */
    'chainName'?: string;
    /**
    * Coordinates of the hotel.
    */
    'coordinates'?: Latlng;
    /**
    * Email address of the hotel.
    */
    'email'?: string;
    /**
    * Hotel id.
    */
    'hotelId'?: string;
    /**
    * Name of the hotel.
    */
    'name': string;
    /**
    * Phone number of the hotel.
    */
    'phone'?: PhoneNumber;
    /**
    * Star rating of the hotel.
    */
    'starRating'?: number;
    'fax'?: Array<PhoneNumber>;
    /**
    * Master chain code of the hotel.
    */
    'masterChainCode'?: string;
    /**
    * Brand name of the hotel.
    */
    'brandName'?: string;
    'amenities'?: Array<HotelAmenities>;
    /**
    * List of amenities provided by the supplier.
    */
    'additionalAmenities'?: Array<string>;
    'imageSets'?: Array<HotelImageSet>;
    'descriptions'?: Array<HotelDescription>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "PostalAddress"
        },
        {
            "name": "chainCode",
            "baseName": "chainCode",
            "type": "string"
        },
        {
            "name": "chainName",
            "baseName": "chainName",
            "type": "string"
        },
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "Latlng"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "hotelId",
            "baseName": "hotelId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "PhoneNumber"
        },
        {
            "name": "starRating",
            "baseName": "starRating",
            "type": "number"
        },
        {
            "name": "fax",
            "baseName": "fax",
            "type": "Array<PhoneNumber>"
        },
        {
            "name": "masterChainCode",
            "baseName": "masterChainCode",
            "type": "string"
        },
        {
            "name": "brandName",
            "baseName": "brandName",
            "type": "string"
        },
        {
            "name": "amenities",
            "baseName": "amenities",
            "type": "Array<HotelAmenities>"
        },
        {
            "name": "additionalAmenities",
            "baseName": "additionalAmenities",
            "type": "Array<string>"
        },
        {
            "name": "imageSets",
            "baseName": "imageSets",
            "type": "Array<HotelImageSet>"
        },
        {
            "name": "descriptions",
            "baseName": "descriptions",
            "type": "Array<HotelDescription>"
        }    ];

    static getAttributeTypeMap() {
        return HotelInfo.attributeTypeMap;
    }
}

