/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Preferred hotel amenity.
*/
export enum HotelPrefAmenity {
    Parking = <any> 'PARKING',
    FreeParking = <any> 'FREE_PARKING',
    FreeBreakfast = <any> 'FREE_BREAKFAST',
    Pool = <any> 'POOL',
    Wifi = <any> 'WIFI',
    FitnessCenter = <any> 'FITNESS_CENTER',
    FamilyFriendly = <any> 'FAMILY_FRIENDLY',
    Reception = <any> 'RECEPTION',
    Spa = <any> 'SPA',
    Restaurant = <any> 'RESTAURANT',
    Bar = <any> 'BAR',
    Transportation = <any> 'TRANSPORTATION',
    PetFriendly = <any> 'PET_FRIENDLY',
    BusinessCenter = <any> 'BUSINESS_CENTER',
    AirConditioning = <any> 'AIR_CONDITIONING',
    BeachAccess = <any> 'BEACH_ACCESS',
    LaundryServices = <any> 'LAUNDRY_SERVICES',
    RoomService = <any> 'ROOM_SERVICE',
    Accessible = <any> 'ACCESSIBLE'
}
