/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConditionalRate } from './conditionalRate';
import { HotelBrand } from './hotelBrand';
import { HotelChain } from './hotelChain';
import { HotelPrefAmenity } from './hotelPrefAmenity';
import { RoomPreference } from './roomPreference';

/**
* Travel preferences related to hotel.
*/
export class HotelPref {
    /**
    * A list of hotel parent chains.
    */
    'hotelParentChains'?: Array<HotelChain>;
    /**
    * A list of hotel brands.
    */
    'hotelBrands'?: Array<HotelBrand>;
    /**
    * A list of HotelAmenities.
    */
    'hotelAmenityTypes'?: Array<HotelPrefAmenity>;
    'roomPreference'?: RoomPreference;
    /**
    * A list of conditional rates for rail.
    */
    'conditionalRates'?: Array<ConditionalRate>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hotelParentChains",
            "baseName": "hotelParentChains",
            "type": "Array<HotelChain>"
        },
        {
            "name": "hotelBrands",
            "baseName": "hotelBrands",
            "type": "Array<HotelBrand>"
        },
        {
            "name": "hotelAmenityTypes",
            "baseName": "hotelAmenityTypes",
            "type": "Array<HotelPrefAmenity>"
        },
        {
            "name": "roomPreference",
            "baseName": "roomPreference",
            "type": "RoomPreference"
        },
        {
            "name": "conditionalRates",
            "baseName": "conditionalRates",
            "type": "Array<ConditionalRate>"
        }    ];

    static getAttributeTypeMap() {
        return HotelPref.attributeTypeMap;
    }
}

