/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Hotel description
*/
export class HotelDescription {
    /**
    * Hotel description type
    */
    'type'?: HotelDescription.TypeEnum;
    /**
    * Hotel description value
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "HotelDescription.TypeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HotelDescription.attributeTypeMap;
    }
}

export namespace HotelDescription {
    export enum TypeEnum {
        General = <any> 'GENERAL',
        Alerts = <any> 'ALERTS',
        Dining = <any> 'DINING',
        Facilities = <any> 'FACILITIES',
        Recreation = <any> 'RECREATION',
        Services = <any> 'SERVICES',
        Attractions = <any> 'ATTRACTIONS',
        CancellationPolicy = <any> 'CANCELLATION_POLICY',
        DepositPolicy = <any> 'DEPOSIT_POLICY',
        Directions = <any> 'DIRECTIONS',
        Policies = <any> 'POLICIES',
        Safety = <any> 'SAFETY',
        Transportation = <any> 'TRANSPORTATION'
    }
}
