/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HotelImageCategory } from './hotelImageCategory';
import { ImageGroup } from './imageGroup';

/**
* Object containing details of images of different for a given category.
*/
export class HotelImageSet {
    'category': HotelImageCategory;
    'imageGroup': ImageGroup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "HotelImageCategory"
        },
        {
            "name": "imageGroup",
            "baseName": "imageGroup",
            "type": "ImageGroup"
        }    ];

    static getAttributeTypeMap() {
        return HotelImageSet.attributeTypeMap;
    }
}

export namespace HotelImageSet {
}
