/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventBookingWindow } from './eventBookingWindow';
import { HotelInfo } from './hotelInfo';

/**
* Hotel related guidelines
*/
export class HotelBookingGuideline {
    /**
    * List of allowed Hotel details for the event
    */
    'allowedHotels'?: Array<HotelInfo>;
    'checkinBookingWindow': EventBookingWindow;
    'checkoutBookingWindow': EventBookingWindow;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedHotels",
            "baseName": "allowedHotels",
            "type": "Array<HotelInfo>"
        },
        {
            "name": "checkinBookingWindow",
            "baseName": "checkinBookingWindow",
            "type": "EventBookingWindow"
        },
        {
            "name": "checkoutBookingWindow",
            "baseName": "checkoutBookingWindow",
            "type": "EventBookingWindow"
        }    ];

    static getAttributeTypeMap() {
        return HotelBookingGuideline.attributeTypeMap;
    }
}

