/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The chain of hotel.
*/
export class HotelChain {
    /**
    * The code of hotel chain.
    */
    'chainCode'?: string;
    /**
    * The name of hotel chain.
    */
    'chainName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainCode",
            "baseName": "chainCode",
            "type": "string"
        },
        {
            "name": "chainName",
            "baseName": "chainName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HotelChain.attributeTypeMap;
    }
}

