/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Occupancy information
*/
export class HotelOccupancy {
    /**
    * Number of adults in the hotel pnr
    */
    'numAdults'?: number;
    /**
    * Number of children in the hotel pnr
    */
    'numChildren'?: number;
    'childAges'?: Array<number>;
    /**
    * Number of infants in the hotel pnr
    */
    'numInfants'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numAdults",
            "baseName": "numAdults",
            "type": "number"
        },
        {
            "name": "numChildren",
            "baseName": "numChildren",
            "type": "number"
        },
        {
            "name": "childAges",
            "baseName": "childAges",
            "type": "Array<number>"
        },
        {
            "name": "numInfants",
            "baseName": "numInfants",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return HotelOccupancy.attributeTypeMap;
    }
}

