/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ImmigrationDocument } from './immigrationDocument';
import { ImmigrationDocumentWrapper } from './immigrationDocumentWrapper';
import { KnownTravelerNumber } from './knownTravelerNumber';
import { KnownTravelerNumberWrapper } from './knownTravelerNumberWrapper';
import { NationalDoc } from './nationalDoc';
import { NationalDocWrapper } from './nationalDocWrapper';
import { Passport } from './passport';
import { PassportWrapper } from './passportWrapper';
import { RedressNumber } from './redressNumber';
import { RedressNumberWrapper } from './redressNumberWrapper';

/**
* Identity document details. Currently supported documents are passport, immigration document,  known traveler number, redress number and national document. 
*/
export class IdentityDocument {
    'passport'?: Passport;
    'immigrationDoc'?: ImmigrationDocument;
    'redress'?: RedressNumber;
    'ktn'?: KnownTravelerNumber;
    'nationalDoc'?: NationalDoc;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "passport",
            "baseName": "passport",
            "type": "Passport"
        },
        {
            "name": "immigrationDoc",
            "baseName": "immigrationDoc",
            "type": "ImmigrationDocument"
        },
        {
            "name": "redress",
            "baseName": "redress",
            "type": "RedressNumber"
        },
        {
            "name": "ktn",
            "baseName": "ktn",
            "type": "KnownTravelerNumber"
        },
        {
            "name": "nationalDoc",
            "baseName": "nationalDoc",
            "type": "NationalDoc"
        }    ];

    static getAttributeTypeMap() {
        return IdentityDocument.attributeTypeMap;
    }
}

