/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Image } from './image';

/**
* Contains different sizes of the same image.
*/
export class ImageGroup {
    /**
    * Caption for the image.
    */
    'caption'?: string;
    /**
    * List of images.
    */
    'images': Array<Image>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Image>"
        }    ];

    static getAttributeTypeMap() {
        return ImageGroup.attributeTypeMap;
    }
}

