/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceData } from './invoiceData';

/**
* Invoice Data for single invoice
*/
export class Invoice {
    /**
    * The invoice number
    */
    'invoiceNumber': string;
    /**
    * The invoice ID
    */
    'invoiceId': string;
    /**
    * The invoice content
    */
    'data': InvoiceData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceNumber",
            "baseName": "invoiceNumber",
            "type": "string"
        },
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "InvoiceData"
        }    ];

    static getAttributeTypeMap() {
        return Invoice.attributeTypeMap;
    }
}

