/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Invoice } from './invoice';

/**
* Invoice Data List
*/
export class InvoiceDataResponse {
    /**
    * List of invoices which were requested.
    */
    'invoices': Array<Invoice>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoices",
            "baseName": "invoices",
            "type": "Array<Invoice>"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceDataResponse.attributeTypeMap;
    }
}

