/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProductType } from './productType';

export class InvoiceInfo {
    /**
    * The invoice number for an invoice
    */
    'invoiceNumber': string;
    /**
    * Type of product for which invoice is generated.
    */
    'productType': ProductType;
    /**
    * Unique ID of the invoice.
    */
    'invoiceId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoiceNumber",
            "baseName": "invoiceNumber",
            "type": "string"
        },
        {
            "name": "productType",
            "baseName": "productType",
            "type": "ProductType"
        },
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceInfo.attributeTypeMap;
    }
}

export namespace InvoiceInfo {
}
