/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LegMetadata } from './legMetadata';

export class LegMetadataWrapper {
    'legMetadata'?: LegMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legMetadata",
            "baseName": "legMetadata",
            "type": "LegMetadata"
        }    ];

    static getAttributeTypeMap() {
        return LegMetadataWrapper.attributeTypeMap;
    }
}

