/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionRiskAlert } from './connectionRiskAlert';

/**
* Alerts like connection risk for a leg
*/
export class LegUpdates {
    'connectionAlerts'?: Array<ConnectionRiskAlert>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connectionAlerts",
            "baseName": "connectionAlerts",
            "type": "Array<ConnectionRiskAlert>"
        }    ];

    static getAttributeTypeMap() {
        return LegUpdates.attributeTypeMap;
    }
}

