/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Specifies the length or a distance.
*/
export class Length {
    /**
    * Distance from search point.
    */
    'length': number;
    /**
    * Unit of measure being applied.
    */
    'unit': Length.UnitEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "Length.UnitEnum"
        }    ];

    static getAttributeTypeMap() {
        return Length.attributeTypeMap;
    }
}

export namespace Length {
    export enum UnitEnum {
        UnknownUnit = <any> 'UNKNOWN_UNIT',
        Km = <any> 'KM',
        Mile = <any> 'MILE'
    }
}
