/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ElectricVehicle } from './electricVehicle';
import { LimoVendorInfo } from './limoVendorInfo';

/**
* Limo details.
*/
export class LimoDetails {
    /**
    * Limo type.
    */
    'carType': LimoDetails.CarTypeEnum;
    /**
    * Whether the limo is electric.
    */
    'electricVehicle': ElectricVehicle;
    /**
    * Vendor name of the limo.
    */
    'vendorName'?: string;
    /**
    * Vendor details of the limo.
    */
    'limoVendorInfo'?: LimoVendorInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carType",
            "baseName": "carType",
            "type": "LimoDetails.CarTypeEnum"
        },
        {
            "name": "electricVehicle",
            "baseName": "electricVehicle",
            "type": "ElectricVehicle"
        },
        {
            "name": "vendorName",
            "baseName": "vendorName",
            "type": "string"
        },
        {
            "name": "limoVendorInfo",
            "baseName": "limoVendorInfo",
            "type": "LimoVendorInfo"
        }    ];

    static getAttributeTypeMap() {
        return LimoDetails.attributeTypeMap;
    }
}

export namespace LimoDetails {
    export enum CarTypeEnum {
        UnknownCarType = <any> 'UNKNOWN_CAR_TYPE',
        StandardCar = <any> 'STANDARD_CAR',
        ExecutiveCar = <any> 'EXECUTIVE_CAR',
        BusinessVan = <any> 'BUSINESS_VAN',
        FirstClass = <any> 'FIRST_CLASS',
        Suv = <any> 'SUV',
        Sedan = <any> 'SEDAN',
        ExecutiveSedan = <any> 'EXECUTIVE_SEDAN',
        LuxurySedan = <any> 'LUXURY_SEDAN',
        ExecutiveVan = <any> 'EXECUTIVE_VAN'
    }
}
