/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrgTripInfo } from './orgTripInfo';

/**
* Gives Trips and associated Pnr\'s for a certain organisation that are updated after a certain time
*/
export class ListOrganisationTripsResponse {
    'trips'?: Array<OrgTripInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trips",
            "baseName": "trips",
            "type": "Array<OrgTripInfo>"
        }    ];

    static getAttributeTypeMap() {
        return ListOrganisationTripsResponse.attributeTypeMap;
    }
}

