/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomFieldId } from './customFieldId';
import { DateTimeOffset } from './dateTimeOffset';
import { OrganizationId } from './organizationId';

/**
* Request for giving trips and associated Pnr\'s for a certain organisation that are updated after a certain time
*/
export class ListOrganisationTripsRequest {
    'organizationId': OrganizationId;
    'updatedAt'?: DateTimeOffset;
    /**
    * Type of PNR
    */
    'pnrType': ListOrganisationTripsRequest.PnrTypeEnum;
    /**
    * List of custom field IDs to filter
    */
    'customFieldIds'?: Array<CustomFieldId>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "OrganizationId"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "DateTimeOffset"
        },
        {
            "name": "pnrType",
            "baseName": "pnrType",
            "type": "ListOrganisationTripsRequest.PnrTypeEnum"
        },
        {
            "name": "customFieldIds",
            "baseName": "customFieldIds",
            "type": "Array<CustomFieldId>"
        }    ];

    static getAttributeTypeMap() {
        return ListOrganisationTripsRequest.attributeTypeMap;
    }
}

export namespace ListOrganisationTripsRequest {
    export enum PnrTypeEnum {
        Air = <any> 'AIR',
        Car = <any> 'CAR',
        Rail = <any> 'RAIL',
        Hotel = <any> 'HOTEL',
        Limo = <any> 'LIMO',
        All = <any> 'ALL'
    }
}
