/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Loyalty Info details.
*/
export class LoyaltyInfo {
    'appliedTo'?: Array<string>;
    'id': string;
    'issuedBy': string;
    'type': LoyaltyInfo.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appliedTo",
            "baseName": "appliedTo",
            "type": "Array<string>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "issuedBy",
            "baseName": "issuedBy",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "LoyaltyInfo.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return LoyaltyInfo.attributeTypeMap;
    }
}

export namespace LoyaltyInfo {
    export enum TypeEnum {
        UnknownType = <any> 'UNKNOWN_TYPE',
        Air = <any> 'AIR',
        Hotel = <any> 'HOTEL',
        Car = <any> 'CAR',
        Rail = <any> 'RAIL'
    }
}
