/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';

/**
* Additional luggage info
*/
export class LuggageInfo {
    /**
    * Index of leg to which this luggage belongs. If -1, belongs to all legs
    */
    'legIdx'?: number;
    /**
    * Total price
    */
    'amount': Money;
    /**
    * Total weight in Kgs
    */
    'weightKg': number;
    /**
    * Number of bags.
    */
    'numBags'?: number;
    /**
    * Status of baggage
    */
    'status'?: LuggageInfo.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legIdx",
            "baseName": "legIdx",
            "type": "number"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "weightKg",
            "baseName": "weightKg",
            "type": "number"
        },
        {
            "name": "numBags",
            "baseName": "numBags",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "LuggageInfo.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return LuggageInfo.attributeTypeMap;
    }
}

export namespace LuggageInfo {
    export enum StatusEnum {
        Unknown = <any> 'UNKNOWN',
        Confirmed = <any> 'CONFIRMED',
        Pending = <any> 'PENDING',
        Cancelled = <any> 'CANCELLED'
    }
}
