/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ManualVerificationReason } from './manualVerificationReason';

/**
* Represents the intent for manual verification with a remark and a list of reasons.
*/
export class ManualVerificationIntent {
    /**
    * Additional remarks or notes about the verification.
    */
    'remark'?: string;
    /**
    * List of reasons for manual verification.
    */
    'reasons'?: Array<ManualVerificationReason>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string"
        },
        {
            "name": "reasons",
            "baseName": "reasons",
            "type": "Array<ManualVerificationReason>"
        }    ];

    static getAttributeTypeMap() {
        return ManualVerificationIntent.attributeTypeMap;
    }
}

