/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Type of the meal
*/
export enum MealType {
    UnknownMeal = <any> 'UNKNOWN_MEAL',
    Avml = <any> 'AVML',
    Bbml = <any> 'BBML',
    Blml = <any> 'BLML',
    Chml = <any> 'CHML',
    Dbml = <any> 'DBML',
    Fpml = <any> 'FPML',
    Gfml = <any> 'GFML',
    Hfml = <any> 'HFML',
    Hnml = <any> 'HNML',
    Ksml = <any> 'KSML',
    Lcml = <any> 'LCML',
    Lfml = <any> 'LFML',
    Lpml = <any> 'LPML',
    Lsml = <any> 'LSML',
    Moml = <any> 'MOML',
    Nlml = <any> 'NLML',
    Nsml = <any> 'NSML',
    Orml = <any> 'ORML',
    Pfml = <any> 'PFML',
    Rvml = <any> 'RVML',
    Sfml = <any> 'SFML',
    Spml = <any> 'SPML',
    Vgml = <any> 'VGML',
    Vjml = <any> 'VJML',
    Vlml = <any> 'VLML',
    Voml = <any> 'VOML'
}
