/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MealType } from './mealType';

/**
* Meal preferences.
*/
export class MealPref {
    'exclMealPrefs'?: Array<MealType>;
    'inclMealPrefs'?: Array<MealType>;
    'specialMealDescription'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "exclMealPrefs",
            "baseName": "exclMealPrefs",
            "type": "Array<MealType>"
        },
        {
            "name": "inclMealPrefs",
            "baseName": "inclMealPrefs",
            "type": "Array<MealType>"
        },
        {
            "name": "specialMealDescription",
            "baseName": "specialMealDescription",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MealPref.attributeTypeMap;
    }
}

