/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Cost } from './cost';
import { DateTimeLocal } from './dateTimeLocal';
import { PnrStatus } from './pnrStatus';

/**
* Misc info
*/
export class MiscInfo {
    /**
    * Description of the miscellaneous segment.
    */
    'description': string;
    /**
    * End date and time.
    */
    'endDateTime': DateTimeLocal;
    /**
    * Pnr status.
    */
    'pnrStatus'?: PnrStatus;
    /**
    * Miscellaneous segment rate.
    */
    'rate': Cost;
    /**
    * Start date and time.
    */
    'startDateTime': DateTimeLocal;
    /**
    * Miscellaneous segment confirmation number.
    */
    'vendorConfirmationNumber': string;
    /**
    * Sorting priority of this pnr
    */
    'sortingPriority'?: number;
    /**
    * Source status code of the pnr
    */
    'sourceStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "endDateTime",
            "baseName": "endDateTime",
            "type": "DateTimeLocal"
        },
        {
            "name": "pnrStatus",
            "baseName": "pnrStatus",
            "type": "PnrStatus"
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "Cost"
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "DateTimeLocal"
        },
        {
            "name": "vendorConfirmationNumber",
            "baseName": "vendorConfirmationNumber",
            "type": "string"
        },
        {
            "name": "sortingPriority",
            "baseName": "sortingPriority",
            "type": "number"
        },
        {
            "name": "sourceStatus",
            "baseName": "sourceStatus",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MiscInfo.attributeTypeMap;
    }
}

export namespace MiscInfo {
}
