/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethod } from './paymentMethod';

export class MoneyOtherCoinageInner {
    /**
    * Payment method
    */
    'coinageCode'?: PaymentMethod;
    'amount'?: number;
    /**
    * 1 coin in this system equals to how many currency value
    */
    'conversionRate'?: number;
    /**
    * 1 coin in this system equals to how many currency value
    */
    'preferredCurrencyConversionRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "coinageCode",
            "baseName": "coinageCode",
            "type": "PaymentMethod"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "conversionRate",
            "baseName": "conversionRate",
            "type": "number"
        },
        {
            "name": "preferredCurrencyConversionRate",
            "baseName": "preferredCurrencyConversionRate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MoneyOtherCoinageInner.attributeTypeMap;
    }
}

export namespace MoneyOtherCoinageInner {
}
