/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Suffix for name
*/
export enum NameSuffix {
    NameSuffixUnknown = <any> 'NAME_SUFFIX_UNKNOWN',
    Sr = <any> 'SR',
    Jr = <any> 'JR',
    Md = <any> 'MD',
    Phd = <any> 'PHD',
    Ii = <any> 'II',
    Iii = <any> 'III',
    Iv = <any> 'IV',
    Do = <any> 'DO',
    Atty = <any> 'ATTY'
}
