/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NameSuffix } from './nameSuffix';

/**
* Full name containing first, middle, last (family) names, and suffix.
*/
export class Name {
    /**
    * Last (family) name.
    */
    'family1': string;
    'family2'?: string;
    /**
    * First (given) name.
    */
    'given': string;
    /**
    * Middle name.
    */
    'middle'?: string;
    /**
    * Suffix used with the name. For example SR or JR.
    */
    'suffix'?: NameSuffix;
    /**
    * Informal preferred name added by traveler. This is not used on any PNR or tickets
    */
    'preferred'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "family1",
            "baseName": "family1",
            "type": "string"
        },
        {
            "name": "family2",
            "baseName": "family2",
            "type": "string"
        },
        {
            "name": "given",
            "baseName": "given",
            "type": "string"
        },
        {
            "name": "middle",
            "baseName": "middle",
            "type": "string"
        },
        {
            "name": "suffix",
            "baseName": "suffix",
            "type": "NameSuffix"
        },
        {
            "name": "preferred",
            "baseName": "preferred",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Name.attributeTypeMap;
    }
}

export namespace Name {
}
