/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateTimeOffset } from './dateTimeOffset';

/**
* Date time in UTC till when this cancellation offer is valid. For example void window expiry. 
*/
export class OfferExpiryInfo {
    'dateTime': DateTimeOffset;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateTime",
            "baseName": "dateTime",
            "type": "DateTimeOffset"
        }    ];

    static getAttributeTypeMap() {
        return OfferExpiryInfo.attributeTypeMap;
    }
}

