/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OfficeId } from './officeId';

export class OfficeIdListWrapper {
    /**
    * A list of office IDs.
    */
    'officeIdList'?: Array<OfficeId>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "officeIdList",
            "baseName": "officeIdList",
            "type": "Array<OfficeId>"
        }    ];

    static getAttributeTypeMap() {
        return OfficeIdListWrapper.attributeTypeMap;
    }
}

