/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Answer option for a question
*/
export class Option {
    /**
    * The code which is sent in answer response.
    */
    'displayCode': string;
    /**
    * The text to be displayed to the user beside this option.
    */
    'displayValue'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayCode",
            "baseName": "displayCode",
            "type": "string"
        },
        {
            "name": "displayValue",
            "baseName": "displayValue",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Option.attributeTypeMap;
    }
}

