/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PnrInfo } from './pnrInfo';

/**
* Trips and PNRs of a particular organistion
*/
export class OrgTripInfo {
    /**
    * Spotnana trip ID
    */
    'tripId': string;
    /**
    * Pnr Info for the organisation trips
    */
    'pnrInfos': Array<PnrInfo>;
    /**
    * Trip Name
    */
    'tripName'?: string;
    /**
    * Trip Description
    */
    'tripDescription'?: string;
    /**
    * Application used while creating trip.
    */
    'applicationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tripId",
            "baseName": "tripId",
            "type": "string"
        },
        {
            "name": "pnrInfos",
            "baseName": "pnrInfos",
            "type": "Array<PnrInfo>"
        },
        {
            "name": "tripName",
            "baseName": "tripName",
            "type": "string"
        },
        {
            "name": "tripDescription",
            "baseName": "tripDescription",
            "type": "string"
        },
        {
            "name": "applicationId",
            "baseName": "applicationId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrgTripInfo.attributeTypeMap;
    }
}

