/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Type of passenger
*/
export enum PassengerType {
    UnknownPassengerType = <any> 'UNKNOWN_PASSENGER_TYPE',
    Adult = <any> 'ADULT',
    Child = <any> 'CHILD',
    Infant = <any> 'INFANT',
    InfantOnLap = <any> 'INFANT_ON_LAP',
    Youth = <any> 'YOUTH',
    Senior = <any> 'SENIOR',
    Teen = <any> 'TEEN'
}
