/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FormOfPayment } from './formOfPayment';
import { Money } from './money';

export class PaymentInfo1 {
    /**
    * Form of payment
    */
    'fop': FormOfPayment;
    /**
    * Total charge for this FOP
    */
    'totalCharge': Money;
    /**
    * Total refund for this FOP
    */
    'totalRefund'?: Money;
    /**
    * Total charge - total refund
    */
    'netCharge'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fop",
            "baseName": "fop",
            "type": "FormOfPayment"
        },
        {
            "name": "totalCharge",
            "baseName": "totalCharge",
            "type": "Money"
        },
        {
            "name": "totalRefund",
            "baseName": "totalRefund",
            "type": "Money"
        },
        {
            "name": "netCharge",
            "baseName": "netCharge",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return PaymentInfo1.attributeTypeMap;
    }
}

