/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Card } from './card';
import { CreditCardAccess } from './creditCardAccess';
import { CreditCardAccessType } from './creditCardAccessType';

/**
* Payment information.
*/
export class PaymentInfo {
    'applicableTo'?: Array<PaymentInfo.ApplicableToEnum>;
    'card': Card;
    'accessType'?: CreditCardAccessType;
    'access'?: CreditCardAccess;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applicableTo",
            "baseName": "applicableTo",
            "type": "Array<PaymentInfo.ApplicableToEnum>"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "Card"
        },
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "CreditCardAccessType"
        },
        {
            "name": "access",
            "baseName": "access",
            "type": "CreditCardAccess"
        }    ];

    static getAttributeTypeMap() {
        return PaymentInfo.attributeTypeMap;
    }
}

export namespace PaymentInfo {
    export enum ApplicableToEnum {
        UnknownApplicableTo = <any> 'UNKNOWN_APPLICABLE_TO',
        Air = <any> 'AIR',
        Hotel = <any> 'HOTEL',
        Rail = <any> 'RAIL',
        Car = <any> 'CAR',
        ServiceFee = <any> 'SERVICE_FEE'
    }
}
