/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardMetadata2 } from './cardMetadata2';
import { PaymentMetadataCustomPaymentMethodMetadata } from './paymentMetadataCustomPaymentMethodMetadata';
import { VendorProgramPaymentMetadata2 } from './vendorProgramPaymentMetadata2';
import { VirtualCardPaymentMetadata } from './virtualCardPaymentMetadata';

/**
* Payment metadata related to form of payment
*/
export class PaymentMetadata {
    'customPaymentMethodMetadata'?: PaymentMetadataCustomPaymentMethodMetadata;
    'vendorProgramPaymentMetadata'?: VendorProgramPaymentMetadata2;
    'virtualCardMetadata'?: VirtualCardPaymentMetadata;
    'cardMetadata'?: CardMetadata2;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customPaymentMethodMetadata",
            "baseName": "customPaymentMethodMetadata",
            "type": "PaymentMetadataCustomPaymentMethodMetadata"
        },
        {
            "name": "vendorProgramPaymentMetadata",
            "baseName": "vendorProgramPaymentMetadata",
            "type": "VendorProgramPaymentMetadata2"
        },
        {
            "name": "virtualCardMetadata",
            "baseName": "virtualCardMetadata",
            "type": "VirtualCardPaymentMetadata"
        },
        {
            "name": "cardMetadata",
            "baseName": "cardMetadata",
            "type": "CardMetadata2"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMetadata.attributeTypeMap;
    }
}

