/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FailureReason } from './failureReason';
import { GatewayInfo } from './gatewayInfo';

/**
* Payment transaction information
*/
export class PaymentTransactionInfo {
    /**
    * Payment transaction reference
    */
    'paymentReference'?: string;
    'gatewayInfo'?: GatewayInfo;
    'failureReason'?: FailureReason;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentReference",
            "baseName": "paymentReference",
            "type": "string"
        },
        {
            "name": "gatewayInfo",
            "baseName": "gatewayInfo",
            "type": "GatewayInfo"
        },
        {
            "name": "failureReason",
            "baseName": "failureReason",
            "type": "FailureReason"
        }    ];

    static getAttributeTypeMap() {
        return PaymentTransactionInfo.attributeTypeMap;
    }
}

