/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RequestedByDetails } from './requestedByDetails';

/**
* Information about pnr creation
*/
export class PnrCreationDetails {
    'requestedByDetails'?: RequestedByDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestedByDetails",
            "baseName": "requestedByDetails",
            "type": "RequestedByDetails"
        }    ];

    static getAttributeTypeMap() {
        return PnrCreationDetails.attributeTypeMap;
    }
}

