/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelDetail } from './cancelDetail';
import { PnrCancelRequestBookingEmailInfo } from './pnrCancelRequestBookingEmailInfo';

/**
* Request to cancel a PNR or part of PNR object.
*/
export class PnrCancelRequest {
    /**
    * Type of cancellation to be performed. For the NO_REFUND, FULL_REFUND and FULL_CREDIT cancellation types, if no cancellationDetails are provided, we assume the entire PNR is being canceled. If the cancellation type is FULL_CREDIT, we will also assume the credits created will have 0 penalty and an expiry date of 1 year from the issue date of the ticket. 
    */
    'cancellationType'?: PnrCancelRequest.CancellationTypeEnum;
    /**
    * List of object to be cancelled and their associated refund details.
    */
    'cancellationDetails'?: Array<CancelDetail>;
    'bookingEmailInfo'?: PnrCancelRequestBookingEmailInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancellationType",
            "baseName": "cancellationType",
            "type": "PnrCancelRequest.CancellationTypeEnum"
        },
        {
            "name": "cancellationDetails",
            "baseName": "cancellationDetails",
            "type": "Array<CancelDetail>"
        },
        {
            "name": "bookingEmailInfo",
            "baseName": "bookingEmailInfo",
            "type": "PnrCancelRequestBookingEmailInfo"
        }    ];

    static getAttributeTypeMap() {
        return PnrCancelRequest.attributeTypeMap;
    }
}

export namespace PnrCancelRequest {
    export enum CancellationTypeEnum {
        NoRefund = <any> 'NO_REFUND',
        FullRefund = <any> 'FULL_REFUND',
        PartialRefund = <any> 'PARTIAL_REFUND',
        FullCredit = <any> 'FULL_CREDIT'
    }
}
