/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancellationDetails } from './cancellationDetails';

/**
* Cancellation details for a booking.
*/
export class PnrCancellationDetails {
    /**
    * PNR ID for the booking.
    */
    'pnrId': string;
    /**
    * Trip ID for the booking.
    */
    'tripId': string;
    /**
    * Cancellation details for this booking.
    */
    'cancellationDetails'?: CancellationDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pnrId",
            "baseName": "pnrId",
            "type": "string"
        },
        {
            "name": "tripId",
            "baseName": "tripId",
            "type": "string"
        },
        {
            "name": "cancellationDetails",
            "baseName": "cancellationDetails",
            "type": "CancellationDetails"
        }    ];

    static getAttributeTypeMap() {
        return PnrCancellationDetails.attributeTypeMap;
    }
}

