/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* PNR related external information
*/
export class PnrDataExternalInfo {
    /**
    * External Pnr ID
    */
    'externalPnrId'?: string;
    /**
    * External Pnr Version
    */
    'externalPnrVersion'?: number;
    /**
    * External url information to be attached for pnr
    */
    'externalUrlMetadata'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalPnrId",
            "baseName": "externalPnrId",
            "type": "string"
        },
        {
            "name": "externalPnrVersion",
            "baseName": "externalPnrVersion",
            "type": "number"
        },
        {
            "name": "externalUrlMetadata",
            "baseName": "externalUrlMetadata",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PnrDataExternalInfo.attributeTypeMap;
    }
}

