/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PnrPolicyId } from './pnrPolicyId';
import { PolicyRuleResultInfo } from './policyRuleResultInfo';

/**
* Policy Info applicable for the associated itinerary
*/
export class PnrPolicyInfo {
    /**
    * List of policies applied to the itinerary.
    */
    'policies'?: Array<PnrPolicyId>;
    'ruleResultInfos'?: Array<PolicyRuleResultInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "policies",
            "baseName": "policies",
            "type": "Array<PnrPolicyId>"
        },
        {
            "name": "ruleResultInfos",
            "baseName": "ruleResultInfos",
            "type": "Array<PolicyRuleResultInfo>"
        }    ];

    static getAttributeTypeMap() {
        return PnrPolicyInfo.attributeTypeMap;
    }
}

