/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Pnr Policy id
*/
export class PnrPolicyId {
    /**
    * Policy id
    */
    'id': string;
    /**
    * version of the policy
    */
    'version': string;
    /**
    * Name of the policy applied.
    */
    'policyName'?: string;
    'approvalType'?: PnrPolicyId.ApprovalTypeEnum;
    'policyType'?: PnrPolicyId.PolicyTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "policyName",
            "baseName": "policyName",
            "type": "string"
        },
        {
            "name": "approvalType",
            "baseName": "approvalType",
            "type": "PnrPolicyId.ApprovalTypeEnum"
        },
        {
            "name": "policyType",
            "baseName": "policyType",
            "type": "PnrPolicyId.PolicyTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PnrPolicyId.attributeTypeMap;
    }
}

export namespace PnrPolicyId {
    export enum ApprovalTypeEnum {
        HardApproval = <any> 'HARD_APPROVAL',
        SoftApproval = <any> 'SOFT_APPROVAL',
        PassiveApproval = <any> 'PASSIVE_APPROVAL'
    }
    export enum PolicyTypeEnum {
        Global = <any> 'GLOBAL',
        Default = <any> 'DEFAULT',
        Group = <any> 'GROUP'
    }
}
