/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Tax1 } from './tax1';

/**
* Tax breakdown information for this ticket
*/
export class PnrTaxBreakdown {
    /**
    * List of taxes for this ticket
    */
    'tax': Array<Tax1>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tax",
            "baseName": "tax",
            "type": "Array<Tax1>"
        }    ];

    static getAttributeTypeMap() {
        return PnrTaxBreakdown.attributeTypeMap;
    }
}

