/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PolicyTakeApprovalAction } from './policyTakeApprovalAction';

export class PolicyTakeApprovalActionWrapper {
    'takeApproval'?: PolicyTakeApprovalAction;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "takeApproval",
            "baseName": "takeApproval",
            "type": "PolicyTakeApprovalAction"
        }    ];

    static getAttributeTypeMap() {
        return PolicyTakeApprovalActionWrapper.attributeTypeMap;
    }
}

