/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This contains the enum mentioning the policy rule which was violated.
*/
export enum PolicyPredicate {
    UnknownPredicateString = <any> 'UNKNOWN_PREDICATE_STRING',
    MaxFarePerTravellerViolation = <any> 'MAX_FARE_PER_TRAVELLER_VIOLATION',
    FareMoreThanMinimum = <any> 'FARE_MORE_THAN_MINIMUM',
    FareMoreThanMedian = <any> 'FARE_MORE_THAN_MEDIAN',
    FareLessThanMedian = <any> 'FARE_LESS_THAN_MEDIAN',
    FareMoreThanLlf = <any> 'FARE_MORE_THAN_LLF',
    MaxFarePerTravellerViolationIncludingTax = <any> 'MAX_FARE_PER_TRAVELLER_VIOLATION_INCLUDING_TAX',
    MaxFarePerTravellerViolationExcludingTax = <any> 'MAX_FARE_PER_TRAVELLER_VIOLATION_EXCLUDING_TAX',
    HotelPaymentOptionsViolation = <any> 'HOTEL_PAYMENT_OPTIONS_VIOLATION',
    RailBookingWindowGapViolation = <any> 'RAIL_BOOKING_WINDOW_GAP_VIOLATION',
    RailTravelClassViolation = <any> 'RAIL_TRAVEL_CLASS_VIOLATION',
    RailTicketRefundableViolation = <any> 'RAIL_TICKET_REFUNDABLE_VIOLATION',
    RailMaxBookingPriceViolationIncludingTax = <any> 'RAIL_MAX_BOOKING_PRICE_VIOLATION_INCLUDING_TAX',
    RailMaxBookingPriceViolationExcludingTax = <any> 'RAIL_MAX_BOOKING_PRICE_VIOLATION_EXCLUDING_TAX',
    AirMaxPriceMoreThanLlfViolationIncludingTax = <any> 'AIR_MAX_PRICE_MORE_THAN_LLF_VIOLATION_INCLUDING_TAX',
    AirMaxPriceMoreThanLlfViolationExcludingTax = <any> 'AIR_MAX_PRICE_MORE_THAN_LLF_VIOLATION_EXCLUDING_TAX',
    HotelRestrictedKeywordsViolation = <any> 'HOTEL_RESTRICTED_KEYWORDS_VIOLATION',
    RestrictedLocationViolation = <any> 'RESTRICTED_LOCATION_VIOLATION',
    FlightAdvanceBookingWindowDomesticViolation = <any> 'FLIGHT_ADVANCE_BOOKING_WINDOW_DOMESTIC_VIOLATION',
    FlightAdvanceBookingWindowInternationalViolation = <any> 'FLIGHT_ADVANCE_BOOKING_WINDOW_INTERNATIONAL_VIOLATION',
    FlightAdvanceBookingWindowViolation = <any> 'FLIGHT_ADVANCE_BOOKING_WINDOW_VIOLATION',
    ItineraryWithinEventTravelWindow = <any> 'ITINERARY_WITHIN_EVENT_TRAVEL_WINDOW',
    HotelInAllowedHotelList = <any> 'HOTEL_IN_ALLOWED_HOTEL_LIST',
    PaymentAccessViolation = <any> 'PAYMENT_ACCESS_VIOLATION',
    AirportInAllowedAirportList = <any> 'AIRPORT_IN_ALLOWED_AIRPORT_LIST',
    ItineraryTypeIsNotInAllowedBookingTypes = <any> 'ITINERARY_TYPE_IS_NOT_IN_ALLOWED_BOOKING_TYPES',
    PaymentAirAddonViolation = <any> 'PAYMENT_AIR_ADDON_VIOLATION',
    MaxHotelBookingPriceIncludingTax = <any> 'MAX_HOTEL_BOOKING_PRICE_INCLUDING_TAX',
    MaxHotelBookingPriceExcludingTax = <any> 'MAX_HOTEL_BOOKING_PRICE_EXCLUDING_TAX',
    AirNumTravelersAllowed = <any> 'AIR_NUM_TRAVELERS_ALLOWED',
    PreferredVendorViolation = <any> 'PREFERRED_VENDOR_VIOLATION',
    SeatAddonViolation = <any> 'SEAT_ADDON_VIOLATION',
    BaggageAddonViolation = <any> 'BAGGAGE_ADDON_VIOLATION',
    EarlyBirdAddonViolation = <any> 'EARLY_BIRD_ADDON_VIOLATION',
    WifiAddonViolation = <any> 'WIFI_ADDON_VIOLATION',
    RestrictedBookingViolation = <any> 'RESTRICTED_BOOKING_VIOLATION',
    HighestAllowedCabinViolation = <any> 'HIGHEST_ALLOWED_CABIN_VIOLATION'
}
