/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PreferredLocationLabel } from './preferredLocationLabel';

/**
* Rail station preferred by traveler.
*/
export class PreferredRailStation {
    /**
    * Rail station name.
    */
    'stationName'?: string;
    /**
    * Rail station code.
    */
    'stationCode': string;
    /**
    * Name of city where the rail station is located.
    */
    'cityName'?: string;
    /**
    * Alpha-2 country code where the rail station is located.
    */
    'countryCode'?: string;
    'label': PreferredLocationLabel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stationName",
            "baseName": "stationName",
            "type": "string"
        },
        {
            "name": "stationCode",
            "baseName": "stationCode",
            "type": "string"
        },
        {
            "name": "cityName",
            "baseName": "cityName",
            "type": "string"
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "PreferredLocationLabel"
        }    ];

    static getAttributeTypeMap() {
        return PreferredRailStation.attributeTypeMap;
    }
}

export namespace PreferredRailStation {
}
