/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PreferredLocationLabel } from './preferredLocationLabel';

/**
* Airport preferred by traveler.
*/
export class PreferredAirport {
    /**
    * Airport name.
    */
    'airportName'?: string;
    /**
    * IATA airport code.
    */
    'airportCode': string;
    'label': PreferredLocationLabel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airportName",
            "baseName": "airportName",
            "type": "string"
        },
        {
            "name": "airportCode",
            "baseName": "airportCode",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "PreferredLocationLabel"
        }    ];

    static getAttributeTypeMap() {
        return PreferredAirport.attributeTypeMap;
    }
}

export namespace PreferredAirport {
}
