/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The label of preferred airport or rail station.
*/
export enum PreferredLocationLabel {
    Home = <any> 'HOME',
    Work = <any> 'WORK',
    Other = <any> 'OTHER'
}
