/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Descriptor for programs details.
*/
export class ProgramDetails {
    /**
    * Contract Id between vendor and the client.
    */
    'uscId': string;
    /**
    * Tracking code to know which company has booked the ticket, it is added to the price quote and ticket.
    */
    'tourCode': string;
    /**
    * Discount code.
    */
    'snapCode': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uscId",
            "baseName": "uscId",
            "type": "string"
        },
        {
            "name": "tourCode",
            "baseName": "tourCode",
            "type": "string"
        },
        {
            "name": "snapCode",
            "baseName": "snapCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProgramDetails.attributeTypeMap;
    }
}

