/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Question types. INPUT_BOX will make user enter a free flowing text. RADIO_BUTTON will have multiple options, user can select only one. CHECKBOX questions contain the possible set of options, from which the user can choose multiple options. CHECKBOX_WITH_PERCENTAGE is similar to checkbox, with the difference being that each option having an additional input field whose values must add up to 100. 
*/
export enum QuestionFormat {
    InputBox = <any> 'INPUT_BOX',
    RadioButton = <any> 'RADIO_BUTTON',
    Checkbox = <any> 'CHECKBOX',
    CheckboxWithPercentage = <any> 'CHECKBOX_WITH_PERCENTAGE'
}
