/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoachPref } from './coachPref';
import { ConditionalRate } from './conditionalRate';
import { PreferredRailStation } from './preferredRailStation';
import { RailTravelClass } from './railTravelClass';
import { SeatPref } from './seatPref';

/**
* Travel preferences related to rail station.
*/
export class RailPref {
    /**
    * A list of user preferred rail stations.
    */
    'preferredRailStations'?: Array<PreferredRailStation>;
    'seatPreference'?: SeatPref;
    /**
    * A list of class of service for rail.
    */
    'travelClasses'?: Array<RailTravelClass>;
    /**
    * A list of coach preference for rail.
    */
    'coachPreferences'?: Array<CoachPref>;
    /**
    * A list of conditional rates for rail.
    */
    'conditionalRates'?: Array<ConditionalRate>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "preferredRailStations",
            "baseName": "preferredRailStations",
            "type": "Array<PreferredRailStation>"
        },
        {
            "name": "seatPreference",
            "baseName": "seatPreference",
            "type": "SeatPref"
        },
        {
            "name": "travelClasses",
            "baseName": "travelClasses",
            "type": "Array<RailTravelClass>"
        },
        {
            "name": "coachPreferences",
            "baseName": "coachPreferences",
            "type": "Array<CoachPref>"
        },
        {
            "name": "conditionalRates",
            "baseName": "conditionalRates",
            "type": "Array<ConditionalRate>"
        }    ];

    static getAttributeTypeMap() {
        return RailPref.attributeTypeMap;
    }
}

