/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TravelCard } from './travelCard';

/**
* Ancillaries for rail.
*/
export class RailAncillary {
    /**
    * Details of the travel cards.
    */
    'travelCard'?: TravelCard;
    /**
    * Type of the ancillary
    */
    'type': RailAncillary.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "travelCard",
            "baseName": "travelCard",
            "type": "TravelCard"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RailAncillary.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RailAncillary.attributeTypeMap;
    }
}

export namespace RailAncillary {
    export enum TypeEnum {
        TravelCard = <any> 'TRAVEL_CARD'
    }
}
