/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Information regarding the vehicle and operator.
*/
export class RailVehicle {
    /**
    * Name of the carrier.
    */
    'carrierName': string;
    /**
    * Timetable ID
    */
    'timetableId': string;
    /**
    * Name of the transport.
    */
    'transportName'?: string;
    /**
    * Type of vehicle.
    */
    'type': RailVehicle.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carrierName",
            "baseName": "carrierName",
            "type": "string"
        },
        {
            "name": "timetableId",
            "baseName": "timetableId",
            "type": "string"
        },
        {
            "name": "transportName",
            "baseName": "transportName",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RailVehicle.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RailVehicle.attributeTypeMap;
    }
}

export namespace RailVehicle {
    export enum TypeEnum {
        Train = <any> 'TRAIN',
        Bus = <any> 'BUS',
        Ferry = <any> 'FERRY',
        Walk = <any> 'WALK',
        Taxi = <any> 'TAXI',
        Tram = <any> 'TRAM',
        Metro = <any> 'METRO',
        Tube = <any> 'TUBE'
    }
}
