/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';
import { Voucher } from './voucher';

/**
* Rate for the itinerary.
*/
export class RailRateInfo {
    /**
    * Base Amount.
    */
    'base': Money;
    /**
    * Fees and Taxes.
    */
    'fees': Money;
    /**
    * Rail Card Discount Amount
    */
    'railCardDiscount'?: Money;
    /**
    * Total Amount.
    */
    'total': Money;
    /**
    * Total Refund Amount.
    */
    'refund'?: Money;
    /**
    * Refund voucher details.
    */
    'refundVoucher'?: Voucher;
    /**
    * Base rate difference during exchange.
    */
    'rateDifference'?: Money;
    /**
    * Total rate difference during exchange.
    */
    'totalRateDifference'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "base",
            "baseName": "base",
            "type": "Money"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "Money"
        },
        {
            "name": "railCardDiscount",
            "baseName": "railCardDiscount",
            "type": "Money"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Money"
        },
        {
            "name": "refund",
            "baseName": "refund",
            "type": "Money"
        },
        {
            "name": "refundVoucher",
            "baseName": "refundVoucher",
            "type": "Voucher"
        },
        {
            "name": "rateDifference",
            "baseName": "rateDifference",
            "type": "Money"
        },
        {
            "name": "totalRateDifference",
            "baseName": "totalRateDifference",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return RailRateInfo.attributeTypeMap;
    }
}

