/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Co2EmissionDetails } from './co2EmissionDetails';
import { PnrStatus } from './pnrStatus';
import { RailFareComposition } from './railFareComposition';

/**
* Journey info
*/
export class RailPnrJourneyInfo {
    /**
    * Status of journey.
    */
    'journeyStatus'?: PnrStatus;
    /**
    * List of indexes of legs covered in the journey.
    */
    'legs': Array<number>;
    /**
    * This sets the CO2 emission info for rail.
    */
    'co2EmissionDetails'?: Co2EmissionDetails;
    /**
    * Sort order of the rail journey on the trips page
    */
    'sortingPriority'?: number;
    /**
    * Indicates whether the fare is through or split.
    */
    'fareComposition'?: RailFareComposition;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "journeyStatus",
            "baseName": "journeyStatus",
            "type": "PnrStatus"
        },
        {
            "name": "legs",
            "baseName": "legs",
            "type": "Array<number>"
        },
        {
            "name": "co2EmissionDetails",
            "baseName": "co2EmissionDetails",
            "type": "Co2EmissionDetails"
        },
        {
            "name": "sortingPriority",
            "baseName": "sortingPriority",
            "type": "number"
        },
        {
            "name": "fareComposition",
            "baseName": "fareComposition",
            "type": "RailFareComposition"
        }    ];

    static getAttributeTypeMap() {
        return RailPnrJourneyInfo.attributeTypeMap;
    }
}

export namespace RailPnrJourneyInfo {
}
