/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RailRefundOption } from './railRefundOption';

/**
* Cancellation details for rail booking.
*/
export class RailCancellationDetails {
    /**
    * Refund options for this booking.
    */
    'refundOptions'?: Array<RailRefundOption>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "refundOptions",
            "baseName": "refundOptions",
            "type": "Array<RailRefundOption>"
        }    ];

    static getAttributeTypeMap() {
        return RailCancellationDetails.attributeTypeMap;
    }
}

