/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RailFareDetail } from './railFareDetail';

/**
* Type of fare.
*/
export class RailFareType {
    /**
    * Description of this fare type.
    */
    'description': string;
    'fareDetails'?: Array<RailFareDetail>;
    /**
    * Summary of the fare
    */
    'fareSummary'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "fareDetails",
            "baseName": "fareDetails",
            "type": "Array<RailFareDetail>"
        },
        {
            "name": "fareSummary",
            "baseName": "fareSummary",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RailFareType.attributeTypeMap;
    }
}

