/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FareAmount } from './fareAmount';
import { Money } from './money';
import { RailRefundVoucher } from './railRefundVoucher';

/**
* Rate information for this refund option.
*/
export class RailRefundRateInfo {
    /**
    * Total fare.
    */
    'totalFare': FareAmount;
    /**
    * Non refundable fare.
    */
    'nonRefundableFare'?: FareAmount;
    /**
    * Cancellation fee.
    */
    'cancellationFee'?: Money;
    /**
    * Total refund amount.
    */
    'refund'?: Money;
    /**
    * Refund voucher details
    */
    'voucher'?: RailRefundVoucher;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalFare",
            "baseName": "totalFare",
            "type": "FareAmount"
        },
        {
            "name": "nonRefundableFare",
            "baseName": "nonRefundableFare",
            "type": "FareAmount"
        },
        {
            "name": "cancellationFee",
            "baseName": "cancellationFee",
            "type": "Money"
        },
        {
            "name": "refund",
            "baseName": "refund",
            "type": "Money"
        },
        {
            "name": "voucher",
            "baseName": "voucher",
            "type": "RailRefundVoucher"
        }    ];

    static getAttributeTypeMap() {
        return RailRefundRateInfo.attributeTypeMap;
    }
}

