/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RailRefundRateInfo } from './railRefundRateInfo';

/**
* Refund options for this rail booking.
*/
export class RailRefundOption {
    /**
    * Refund option id.
    */
    'refundId': string;
    /**
    * Rail refund fare info.
    */
    'refundRateInfo': RailRefundRateInfo;
    /**
    * List of leg indices for the refund option.
    */
    'legs'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "refundId",
            "baseName": "refundId",
            "type": "string"
        },
        {
            "name": "refundRateInfo",
            "baseName": "refundRateInfo",
            "type": "RailRefundRateInfo"
        },
        {
            "name": "legs",
            "baseName": "legs",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return RailRefundOption.attributeTypeMap;
    }
}

