/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HotelRateAssuranceMetadata } from './hotelRateAssuranceMetadata';

/**
* Rate Assurance Rebooking information along with pnr references and savings
*/
export class RebookReference {
    /**
    * Backward reference to the cancelled PNRs (if any) after rebooking.
    */
    'cancelledPnrIds'?: Array<string>;
    /**
    * Forward reference to the rebooked PNR (if any) after cancellation.
    */
    'rebookedPnrId'?: string;
    'hotelRateAssuranceMetadata'?: HotelRateAssuranceMetadata;
    /**
    * Indicates the reason for rebooking.
    */
    'rebookType'?: RebookReference.RebookTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelledPnrIds",
            "baseName": "cancelledPnrIds",
            "type": "Array<string>"
        },
        {
            "name": "rebookedPnrId",
            "baseName": "rebookedPnrId",
            "type": "string"
        },
        {
            "name": "hotelRateAssuranceMetadata",
            "baseName": "hotelRateAssuranceMetadata",
            "type": "HotelRateAssuranceMetadata"
        },
        {
            "name": "rebookType",
            "baseName": "rebookType",
            "type": "RebookReference.RebookTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RebookReference.attributeTypeMap;
    }
}

export namespace RebookReference {
    export enum RebookTypeEnum {
        RateAssurance = <any> 'RATE_ASSURANCE',
        Modify = <any> 'MODIFY'
    }
}
