/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RedressNumber } from './redressNumber';

export class RedressNumberWrapper {
    'redress'?: RedressNumber;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "redress",
            "baseName": "redress",
            "type": "RedressNumber"
        }    ];

    static getAttributeTypeMap() {
        return RedressNumberWrapper.attributeTypeMap;
    }
}

