/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateModel } from './dateModel';
import { FareAmount } from './fareAmount';
import { PnrTaxBreakdown } from './pnrTaxBreakdown';

/**
* Ticket refund info
*/
export class RefundInfo {
    /**
    * The amount refunded back to the client if the ticket was refunded
    */
    'refundAmount': FareAmount;
    /**
    * The date when the refund was issued
    */
    'refundDate'?: DateModel;
    /**
    * Refund penalty
    */
    'penalty'?: FareAmount;
    /**
    * Tax breakdown for the refund amount
    */
    'refundTaxBreakdown'?: PnrTaxBreakdown;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "refundAmount",
            "baseName": "refundAmount",
            "type": "FareAmount"
        },
        {
            "name": "refundDate",
            "baseName": "refundDate",
            "type": "DateModel"
        },
        {
            "name": "penalty",
            "baseName": "penalty",
            "type": "FareAmount"
        },
        {
            "name": "refundTaxBreakdown",
            "baseName": "refundTaxBreakdown",
            "type": "PnrTaxBreakdown"
        }    ];

    static getAttributeTypeMap() {
        return RefundInfo.attributeTypeMap;
    }
}

