/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The region code for which the following invoicing information is applicable.
*/
export enum RegionCode {
    Us = <any> 'US',
    Uk = <any> 'UK',
    Nl = <any> 'NL',
    Sg = <any> 'SG',
    Ca = <any> 'CA'
}
