/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RewardsProgramMetadata } from './rewardsProgramMetadata';

/**
* Wrapper for RewardsProgramMetadata
*/
export class RewardsProgramMetadataWrapper {
    'rewardsProgramMetadata'?: RewardsProgramMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rewardsProgramMetadata",
            "baseName": "rewardsProgramMetadata",
            "type": "RewardsProgramMetadata"
        }    ];

    static getAttributeTypeMap() {
        return RewardsProgramMetadataWrapper.attributeTypeMap;
    }
}

