/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PointsBalance } from './pointsBalance';
import { RewardsProgramType } from './rewardsProgramType';

/**
* Metadata for Rewards Program payment source.
*/
export class RewardsProgramMetadata {
    'type': RewardsProgramType;
    'pointsBalance'?: PointsBalance;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "RewardsProgramType"
        },
        {
            "name": "pointsBalance",
            "baseName": "pointsBalance",
            "type": "PointsBalance"
        }    ];

    static getAttributeTypeMap() {
        return RewardsProgramMetadata.attributeTypeMap;
    }
}

export namespace RewardsProgramMetadata {
}
