/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Room Type
*/
export enum RoomType {
    Room = <any> 'ROOM',
    Suite = <any> 'SUITE',
    Villa = <any> 'VILLA',
    Apartment = <any> 'APARTMENT',
    Cottage = <any> 'COTTAGE',
    Studio = <any> 'STUDIO',
    UnknownRoom = <any> 'UNKNOWN_ROOM'
}
