/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BedType } from './bedType';
import { CancellationPolicy2 } from './cancellationPolicy2';
import { HotelAdditionalDetail } from './hotelAdditionalDetail';
import { HotelCo2EmissionDetail } from './hotelCo2EmissionDetail';
import { HotelImageSet } from './hotelImageSet';
import { HotelRoomAmenity } from './hotelRoomAmenity';
import { HotelRoomMeal } from './hotelRoomMeal';
import { RateInfo } from './rateInfo';
import { RoomAmenitiy } from './roomAmenitiy';
import { RoomRoomInfo } from './roomRoomInfo';

/**
* Room info
*/
export class Room {
    /**
    * Number of rooms.
    */
    'bedCount': number;
    /**
    * Bed type.
    */
    'bedType': BedType;
    /**
    * Room cancellation policy.
    */
    'cancellationPolicy': CancellationPolicy2;
    'rateInfo': RateInfo;
    /**
    * Name of the room.
    */
    'roomName'?: string;
    'imageSets'?: Array<HotelImageSet>;
    /**
    * Details of Meal plan available with the room.
    */
    'meals'?: HotelRoomMeal;
    'roomAmenities'?: Array<RoomAmenitiy>;
    'amenities'?: Array<HotelRoomAmenity>;
    'additionalAmenities'?: Array<string>;
    /**
    * Guarantee type for the booking.
    */
    'guaranteeType'?: Room.GuaranteeTypeEnum;
    'additionalDetails'?: Array<HotelAdditionalDetail>;
    'roomInfo'?: RoomRoomInfo;
    /**
    * The co2 emission detail for the room.
    */
    'co2EmissionDetail'?: HotelCo2EmissionDetail;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bedCount",
            "baseName": "bedCount",
            "type": "number"
        },
        {
            "name": "bedType",
            "baseName": "bedType",
            "type": "BedType"
        },
        {
            "name": "cancellationPolicy",
            "baseName": "cancellationPolicy",
            "type": "CancellationPolicy2"
        },
        {
            "name": "rateInfo",
            "baseName": "rateInfo",
            "type": "RateInfo"
        },
        {
            "name": "roomName",
            "baseName": "roomName",
            "type": "string"
        },
        {
            "name": "imageSets",
            "baseName": "imageSets",
            "type": "Array<HotelImageSet>"
        },
        {
            "name": "meals",
            "baseName": "meals",
            "type": "HotelRoomMeal"
        },
        {
            "name": "roomAmenities",
            "baseName": "roomAmenities",
            "type": "Array<RoomAmenitiy>"
        },
        {
            "name": "amenities",
            "baseName": "amenities",
            "type": "Array<HotelRoomAmenity>"
        },
        {
            "name": "additionalAmenities",
            "baseName": "additionalAmenities",
            "type": "Array<string>"
        },
        {
            "name": "guaranteeType",
            "baseName": "guaranteeType",
            "type": "Room.GuaranteeTypeEnum"
        },
        {
            "name": "additionalDetails",
            "baseName": "additionalDetails",
            "type": "Array<HotelAdditionalDetail>"
        },
        {
            "name": "roomInfo",
            "baseName": "roomInfo",
            "type": "RoomRoomInfo"
        },
        {
            "name": "co2EmissionDetail",
            "baseName": "co2EmissionDetail",
            "type": "HotelCo2EmissionDetail"
        }    ];

    static getAttributeTypeMap() {
        return Room.attributeTypeMap;
    }
}

export namespace Room {
    export enum GuaranteeTypeEnum {
        Guarantee = <any> 'GUARANTEE',
        Deposit = <any> 'DEPOSIT'
    }
}
