/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RoomRoomInfoRoomView } from './roomRoomInfoRoomView';
import { RoomType } from './roomType';

export class RoomRoomInfo {
    'roomType'?: RoomType;
    'typeClassDescription'?: string;
    'roomView'?: RoomRoomInfoRoomView;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "roomType",
            "baseName": "roomType",
            "type": "RoomType"
        },
        {
            "name": "typeClassDescription",
            "baseName": "typeClassDescription",
            "type": "string"
        },
        {
            "name": "roomView",
            "baseName": "roomView",
            "type": "RoomRoomInfoRoomView"
        }    ];

    static getAttributeTypeMap() {
        return RoomRoomInfo.attributeTypeMap;
    }
}

export namespace RoomRoomInfo {
}
