/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Room Class
*/
export enum RoomClass {
    Standard = <any> 'STANDARD',
    Premium = <any> 'PREMIUM',
    Deluxe = <any> 'DELUXE',
    Business = <any> 'BUSINESS',
    Presidential = <any> 'PRESIDENTIAL',
    Superior = <any> 'SUPERIOR',
    Junior = <any> 'JUNIOR',
    Club = <any> 'CLUB',
    Unknown = <any> 'UNKNOWN'
}
