/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum RoomView {
    Unknown = <any> 'UNKNOWN',
    Airport = <any> 'AIRPORT',
    Bay = <any> 'BAY',
    City = <any> 'CITY',
    Courtyard = <any> 'COURTYARD',
    Golf = <any> 'GOLF',
    Harbor = <any> 'HARBOR',
    Intercoastal = <any> 'INTERCOASTAL',
    Lake = <any> 'LAKE',
    Marina = <any> 'MARINA',
    Mountain = <any> 'MOUNTAIN',
    Ocean = <any> 'OCEAN',
    Pool = <any> 'POOL',
    River = <any> 'RIVER',
    Water = <any> 'WATER',
    Beach = <any> 'BEACH',
    Garden = <any> 'GARDEN',
    Park = <any> 'PARK',
    Forest = <any> 'FOREST',
    RainForest = <any> 'RAIN_FOREST',
    Various = <any> 'VARIOUS',
    Limited = <any> 'LIMITED',
    Slope = <any> 'SLOPE',
    Strip = <any> 'STRIP',
    Countryside = <any> 'COUNTRYSIDE',
    Sea = <any> 'SEA',
    Gulf = <any> 'GULF'
}
