/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RoomClass } from './roomClass';
import { RoomView } from './roomView';

export class RoomRoomInfoRoomView {
    'type'?: RoomView;
    'roomClass'?: Array<RoomClass>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "RoomView"
        },
        {
            "name": "roomClass",
            "baseName": "roomClass",
            "type": "Array<RoomClass>"
        }    ];

    static getAttributeTypeMap() {
        return RoomRoomInfoRoomView.attributeTypeMap;
    }
}

export namespace RoomRoomInfoRoomView {
}
