/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Refund information if applicable for this ticket
*/
export class ScheduleChangeRefundInfo {
    /**
    * Whether refund is allowed if user denies schedule change/cancels the flight
    */
    'isRefundAllowed'?: boolean;
    /**
    * Waiver code for refund if applicable
    */
    'refundWaiverCode'?: string;
    /**
    * Waiver code for exchange if available
    */
    'exchangeWaiverCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isRefundAllowed",
            "baseName": "isRefundAllowed",
            "type": "boolean"
        },
        {
            "name": "refundWaiverCode",
            "baseName": "refundWaiverCode",
            "type": "string"
        },
        {
            "name": "exchangeWaiverCode",
            "baseName": "exchangeWaiverCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScheduleChangeRefundInfo.attributeTypeMap;
    }
}

