/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Seat location preference.
*/
export class SeatLocationPref {
    'cabins'?: Array<SeatLocationPref.CabinsEnum>;
    'isBulkHeadPref'?: boolean;
    'maxFlightDurationInHours'?: number;
    'position'?: SeatLocationPref.PositionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cabins",
            "baseName": "cabins",
            "type": "Array<SeatLocationPref.CabinsEnum>"
        },
        {
            "name": "isBulkHeadPref",
            "baseName": "isBulkHeadPref",
            "type": "boolean"
        },
        {
            "name": "maxFlightDurationInHours",
            "baseName": "maxFlightDurationInHours",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "SeatLocationPref.PositionEnum"
        }    ];

    static getAttributeTypeMap() {
        return SeatLocationPref.attributeTypeMap;
    }
}

export namespace SeatLocationPref {
    export enum CabinsEnum {
        UnknownCabin = <any> 'UNKNOWN_CABIN',
        Economy = <any> 'ECONOMY',
        PremiumEconomy = <any> 'PREMIUM_ECONOMY',
        Business = <any> 'BUSINESS',
        First = <any> 'FIRST'
    }
    export enum PositionEnum {
        UnknownPosition = <any> 'UNKNOWN_POSITION',
        Aisle = <any> 'AISLE',
        Window = <any> 'WINDOW',
        AisleOrWindow = <any> 'AISLE_OR_WINDOW'
    }
}
