/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CompanyId } from './companyId';
import { SupplierType } from './supplierType';
import { TravelType } from './travelType';

/**
* Secondary service provider TMC info
*/
export class SecondaryServiceProviderTmc {
    /**
    * Id of the service provider TMC.
    */
    'tmcId': CompanyId;
    /**
    * Supplier for which this service provider should be used.
    */
    'supplier': SupplierType;
    /**
    * Travel type for which this service provider should be used.
    */
    'travelType': TravelType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tmcId",
            "baseName": "tmcId",
            "type": "CompanyId"
        },
        {
            "name": "supplier",
            "baseName": "supplier",
            "type": "SupplierType"
        },
        {
            "name": "travelType",
            "baseName": "travelType",
            "type": "TravelType"
        }    ];

    static getAttributeTypeMap() {
        return SecondaryServiceProviderTmc.attributeTypeMap;
    }
}

export namespace SecondaryServiceProviderTmc {
}
