/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';

/**
* Describes the selected payment source for the booking.
*/
export class SelectedPaymentSource {
    /**
    * Unique identifier identifying this payment source.
    */
    'paymentSourceId'?: string;
    /**
    * Url for post payment redirection if payment source navigates user to a third party url
    */
    'postPaymentRedirectionUrl'?: string;
    /**
    * CVV associated with associated payment source, if any.
    */
    'cvv'?: string;
    /**
    * Total amount to be charged for specified payment items.
    */
    'amount'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentSourceId",
            "baseName": "paymentSourceId",
            "type": "string"
        },
        {
            "name": "postPaymentRedirectionUrl",
            "baseName": "postPaymentRedirectionUrl",
            "type": "string"
        },
        {
            "name": "cvv",
            "baseName": "cvv",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return SelectedPaymentSource.attributeTypeMap;
    }
}

