/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdInfo } from './idInfo';

/**
* Entity that sold the items mentioned in the invoice.
*/
export class SellerInfo {
    /**
    * Name of seller, usually a TMC Legal Entity.
    */
    'name': string;
    /**
    * Address of seller.
    */
    'address': string;
    /**
    * Tax number for the seller, for ex GSTN in India
    */
    'taxId'?: string;
    /**
    * The seller ID information.
    */
    'idInfo'?: Array<IdInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "taxId",
            "baseName": "taxId",
            "type": "string"
        },
        {
            "name": "idInfo",
            "baseName": "idInfo",
            "type": "Array<IdInfo>"
        }    ];

    static getAttributeTypeMap() {
        return SellerInfo.attributeTypeMap;
    }
}

