/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Information about shell pnr
*/
export class ShellPnrInfo {
    /**
    * Reason for creating the shell pnr
    */
    'shellPnrCreateReasonType'?: string;
    /**
    * If the reason for creating the shell pnr is chosen as OTHER or CONTENT_NOT_AVAILABLE,  we expect the agent to explain the reason using this free text 
    */
    'createShellPnrReason'?: string;
    /**
    * It will contain the PNR type for different shell PNRs
    */
    'pnrType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shellPnrCreateReasonType",
            "baseName": "shellPnrCreateReasonType",
            "type": "string"
        },
        {
            "name": "createShellPnrReason",
            "baseName": "createShellPnrReason",
            "type": "string"
        },
        {
            "name": "pnrType",
            "baseName": "pnrType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ShellPnrInfo.attributeTypeMap;
    }
}

