/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateTimeLocal } from './dateTimeLocal';
import { SimpleRailStationInfo } from './simpleRailStationInfo';

/**
* The List of legs in the section.
*/
export class SimpleRailLegInfo {
    /**
    * The originating station info of the Leg.
    */
    'originStationInfo': SimpleRailStationInfo;
    /**
    * The destination station info of the Leg.
    */
    'destinationStationInfo': SimpleRailStationInfo;
    /**
    * The departure date and time for the flight.
    */
    'departureDatetime': DateTimeLocal;
    /**
    * The arrival date and time for the flight.
    */
    'arrivalDateTime': DateTimeLocal;
    /**
    * The name of the carrier.
    */
    'carrierName': string;
    /**
    * This field sets the sorting priority of the rail leg to determine its order of display on the trips page. 
    */
    'sortingPriority'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "originStationInfo",
            "baseName": "originStationInfo",
            "type": "SimpleRailStationInfo"
        },
        {
            "name": "destinationStationInfo",
            "baseName": "destinationStationInfo",
            "type": "SimpleRailStationInfo"
        },
        {
            "name": "departureDatetime",
            "baseName": "departureDatetime",
            "type": "DateTimeLocal"
        },
        {
            "name": "arrivalDateTime",
            "baseName": "arrivalDateTime",
            "type": "DateTimeLocal"
        },
        {
            "name": "carrierName",
            "baseName": "carrierName",
            "type": "string"
        },
        {
            "name": "sortingPriority",
            "baseName": "sortingPriority",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SimpleRailLegInfo.attributeTypeMap;
    }
}

