/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateTimeLocal } from './dateTimeLocal';
import { SimpleAirportInfo } from './simpleAirportInfo';

/**
* The basic flight information.
*/
export class SimpleFlightInfo {
    /**
    * The confirmation ID in the vendor system.
    */
    'vendorConfirmationId': string;
    /**
    * The flight number.
    */
    'flightNumber': string;
    /**
    * The operating airline code.
    */
    'airlineCode': string;
    /**
    * The departure airport code.
    */
    'departureAirportInfo': SimpleAirportInfo;
    /**
    * The arrival airport code.
    */
    'arrivalAirportInfo': SimpleAirportInfo;
    /**
    * The departure date and time for the flight.
    */
    'departureDatetime'?: DateTimeLocal;
    /**
    * The arrival date and time for the flight.
    */
    'arrivalDateTime'?: DateTimeLocal;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vendorConfirmationId",
            "baseName": "vendorConfirmationId",
            "type": "string"
        },
        {
            "name": "flightNumber",
            "baseName": "flightNumber",
            "type": "string"
        },
        {
            "name": "airlineCode",
            "baseName": "airlineCode",
            "type": "string"
        },
        {
            "name": "departureAirportInfo",
            "baseName": "departureAirportInfo",
            "type": "SimpleAirportInfo"
        },
        {
            "name": "arrivalAirportInfo",
            "baseName": "arrivalAirportInfo",
            "type": "SimpleAirportInfo"
        },
        {
            "name": "departureDatetime",
            "baseName": "departureDatetime",
            "type": "DateTimeLocal"
        },
        {
            "name": "arrivalDateTime",
            "baseName": "arrivalDateTime",
            "type": "DateTimeLocal"
        }    ];

    static getAttributeTypeMap() {
        return SimpleFlightInfo.attributeTypeMap;
    }
}

