/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SimpleFlightInfo } from './simpleFlightInfo';

/**
* The information related to a leg.
*/
export class SimpleLegInfo {
    'flights': Array<SimpleFlightInfo>;
    /**
    * This field sets the sorting priority of the simple leg to determine its order of display on the trips page. 
    */
    'sortingPriority'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flights",
            "baseName": "flights",
            "type": "Array<SimpleFlightInfo>"
        },
        {
            "name": "sortingPriority",
            "baseName": "sortingPriority",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SimpleLegInfo.attributeTypeMap;
    }
}

