/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SimpleRailLegInfo } from './simpleRailLegInfo';

/**
* The List of sections covered in the itinerary.
*/
export class SimpleSectionInfo {
    /**
    * The confirmation ID in the vendor system.
    */
    'vendorConfirmationId': string;
    /**
    * The information related to the legs in a section.
    */
    'legs': Array<SimpleRailLegInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vendorConfirmationId",
            "baseName": "vendorConfirmationId",
            "type": "string"
        },
        {
            "name": "legs",
            "baseName": "legs",
            "type": "Array<SimpleRailLegInfo>"
        }    ];

    static getAttributeTypeMap() {
        return SimpleSectionInfo.attributeTypeMap;
    }
}

