/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Source Reference Information
*/
export class SourceRefInfo {
    /**
    * Reference Id of the Station
    */
    'stationReferenceId': string;
    /**
    * Inventory Name
    */
    'inventoryName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stationReferenceId",
            "baseName": "stationReferenceId",
            "type": "string"
        },
        {
            "name": "inventoryName",
            "baseName": "inventoryName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SourceRefInfo.attributeTypeMap;
    }
}

