/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Split option details when using a card from a specific card company
*/
export class SplitOptionByCardCompany {
    /**
    * Card company code which allows splitting the payment
    */
    'cardCompanyCode': string;
    'splitWithCardCompanyCodes'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cardCompanyCode",
            "baseName": "cardCompanyCode",
            "type": "string"
        },
        {
            "name": "splitWithCardCompanyCodes",
            "baseName": "splitWithCardCompanyCodes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return SplitOptionByCardCompany.attributeTypeMap;
    }
}

