/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';

/**
* Tax details
*/
export class Tax {
    /**
    * Tax amount
    */
    'amount': Money;
    /**
    * Tax code
    */
    'taxCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "taxCode",
            "baseName": "taxCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Tax.attributeTypeMap;
    }
}

