/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ThirdPartySource {
    UnknownSource = <any> 'UNKNOWN_SOURCE',
    Sabre = <any> 'SABRE',
    TravelFusion = <any> 'TRAVEL_FUSION',
    Avia = <any> 'AVIA',
    Ndc = <any> 'NDC',
    Trainline = <any> 'TRAINLINE',
    AtpcoNdc = <any> 'ATPCO_NDC',
    FarelogixNdc = <any> 'FARELOGIX_NDC',
    Offline = <any> 'OFFLINE',
    Connexus = <any> 'CONNEXUS',
    Routehappy = <any> 'ROUTEHAPPY',
    Amadeus = <any> 'AMADEUS',
    Giata = <any> 'GIATA',
    Qbr = <any> 'QBR',
    Bcd = <any> 'BCD',
    QantasHotels = <any> 'QANTAS_HOTELS',
    Southwest = <any> 'SOUTHWEST',
    Expedia = <any> 'EXPEDIA',
    HotelHub = <any> 'HOTEL_HUB',
    Marriott = <any> 'MARRIOTT',
    Cleartrip = <any> 'CLEARTRIP',
    Kyte = <any> 'KYTE'
}
