/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScheduleChangeRefundInfo } from './scheduleChangeRefundInfo';

/**
* Schedule change information for this ticket
*/
export class TicketScheduleChangeInformation {
    'possibleActions'?: Array<TicketScheduleChangeInformation.PossibleActionsEnum>;
    'refundInfo'?: ScheduleChangeRefundInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "possibleActions",
            "baseName": "possibleActions",
            "type": "Array<TicketScheduleChangeInformation.PossibleActionsEnum>"
        },
        {
            "name": "refundInfo",
            "baseName": "refundInfo",
            "type": "ScheduleChangeRefundInfo"
        }    ];

    static getAttributeTypeMap() {
        return TicketScheduleChangeInformation.attributeTypeMap;
    }
}

export namespace TicketScheduleChangeInformation {
    export enum PossibleActionsEnum {
        AcceptBooking = <any> 'ACCEPT_BOOKING',
        CancelBooking = <any> 'CANCEL_BOOKING',
        ModifyBooking = <any> 'MODIFY_BOOKING',
        ContactAgent = <any> 'CONTACT_AGENT'
    }
}
