/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FareAmount } from './fareAmount';

export class TicketAncillary {
    /**
    * Type of ancillary
    */
    'ancillaryType': TicketAncillary.AncillaryTypeEnum;
    /**
    * Total fare of this ancillary
    */
    'totalFare': FareAmount;
    /**
    * Index of leg to which this ancillary belongs. If an ancillary belongs to all legs, this index should be set to -1
    */
    'legIndex': number;
    /**
    * Index of flight in it\'s leg to which this ancillary belongs. If an ancillary belongs to all flights, this index should be set to -1
    */
    'flightIndex': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ancillaryType",
            "baseName": "ancillaryType",
            "type": "TicketAncillary.AncillaryTypeEnum"
        },
        {
            "name": "totalFare",
            "baseName": "totalFare",
            "type": "FareAmount"
        },
        {
            "name": "legIndex",
            "baseName": "legIndex",
            "type": "number"
        },
        {
            "name": "flightIndex",
            "baseName": "flightIndex",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TicketAncillary.attributeTypeMap;
    }
}

export namespace TicketAncillary {
    export enum AncillaryTypeEnum {
        Unknown = <any> 'UNKNOWN',
        Seat = <any> 'SEAT',
        Luggage = <any> 'LUGGAGE',
        EarlyBird = <any> 'EARLY_BIRD',
        Wifi = <any> 'WIFI',
        CarbonOffset = <any> 'CARBON_OFFSET'
    }
}
