/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CompanyRef } from './companyRef';

/**
* TMC related basic information.
*/
export class TmcBasicInfo {
    /**
    * Contracting TMC is the TMC the user/organization contracted.
    */
    'contractingTmc': CompanyRef;
    /**
    * Booking TMC is the TMC used for the bookings for the user/organization.
    */
    'bookingTmc': CompanyRef;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contractingTmc",
            "baseName": "contractingTmc",
            "type": "CompanyRef"
        },
        {
            "name": "bookingTmc",
            "baseName": "bookingTmc",
            "type": "CompanyRef"
        }    ];

    static getAttributeTypeMap() {
        return TmcBasicInfo.attributeTypeMap;
    }
}

