/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Transmission types.
*/
export enum Transmission {
    UnknownTransmission = <any> 'UNKNOWN_TRANSMISSION',
    ManualUnspecifiedDrive = <any> 'MANUAL_UNSPECIFIED_DRIVE',
    Manual4Wd = <any> 'MANUAL_4WD',
    ManualAwd = <any> 'MANUAL_AWD',
    AutoUnspecifiedDrive = <any> 'AUTO_UNSPECIFIED_DRIVE',
    Auto4Wd = <any> 'AUTO_4WD',
    AutoAwd = <any> 'AUTO_AWD'
}
