/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Reference } from './reference';
import { WorkerType } from './workerType';

/**
* Matching conditions for traveler.
*/
export class TravelerMatchConditions {
    /**
    * Worker types. Users belonging to any of these would match.
    */
    'workerTypes'?: Array<WorkerType>;
    /**
    * Countries.
    */
    'countries'?: Array<string>;
    /**
    * Legal entities
    */
    'legalEntities'?: Array<Reference>;
    /**
    * Departments
    */
    'departments'?: Array<Reference>;
    /**
    * Cost centers
    */
    'costCenters'?: Array<Reference>;
    /**
    * Offices
    */
    'offices'?: Array<Reference>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workerTypes",
            "baseName": "workerTypes",
            "type": "Array<WorkerType>"
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Array<string>"
        },
        {
            "name": "legalEntities",
            "baseName": "legalEntities",
            "type": "Array<Reference>"
        },
        {
            "name": "departments",
            "baseName": "departments",
            "type": "Array<Reference>"
        },
        {
            "name": "costCenters",
            "baseName": "costCenters",
            "type": "Array<Reference>"
        },
        {
            "name": "offices",
            "baseName": "offices",
            "type": "Array<Reference>"
        }    ];

    static getAttributeTypeMap() {
        return TravelerMatchConditions.attributeTypeMap;
    }
}

