/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirVendorCancellationInfo } from './airVendorCancellationInfo';
import { AppliedCreditInfo } from './appliedCreditInfo';
import { BoardingPass } from './boardingPass';
import { Booking } from './booking';
import { PassengerType } from './passengerType';
import { SpecialServiceRequestInfoDetail } from './specialServiceRequestInfoDetail';
import { Ticket } from './ticket';
import { UserId } from './userId';

/**
* Traveler air booking info
*/
export class TravelerInfo {
    'airVendorCancellationInfo'?: AirVendorCancellationInfo;
    /**
    * Index of traveler in travelers list to which this info belongs
    */
    'travelerIdx': number;
    /**
    * User ID of traveler to which this TravelerInfo object belongs
    */
    'userId'?: UserId;
    'paxType'?: PassengerType;
    /**
    * Tickets belonging to this traveler
    */
    'tickets'?: Array<Ticket>;
    /**
    * Boarding pass details.
    */
    'boardingPass'?: Array<BoardingPass>;
    /**
    * Info about items booked for this traveler eg. flights, seats, etc.
    */
    'booking': Booking;
    /**
    * Information about credit redeemed in booking.
    */
    'appliedCredits'?: Array<AppliedCreditInfo>;
    /**
    * List of all the Special Service Requests associated with the traveler.
    */
    'specialServiceRequestInfos'?: Array<SpecialServiceRequestInfoDetail>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airVendorCancellationInfo",
            "baseName": "airVendorCancellationInfo",
            "type": "AirVendorCancellationInfo"
        },
        {
            "name": "travelerIdx",
            "baseName": "travelerIdx",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "paxType",
            "baseName": "paxType",
            "type": "PassengerType"
        },
        {
            "name": "tickets",
            "baseName": "tickets",
            "type": "Array<Ticket>"
        },
        {
            "name": "boardingPass",
            "baseName": "boardingPass",
            "type": "Array<BoardingPass>"
        },
        {
            "name": "booking",
            "baseName": "booking",
            "type": "Booking"
        },
        {
            "name": "appliedCredits",
            "baseName": "appliedCredits",
            "type": "Array<AppliedCreditInfo>"
        },
        {
            "name": "specialServiceRequestInfos",
            "baseName": "specialServiceRequestInfos",
            "type": "Array<SpecialServiceRequestInfoDetail>"
        }    ];

    static getAttributeTypeMap() {
        return TravelerInfo.attributeTypeMap;
    }
}

export namespace TravelerInfo {
}
