/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Rail Travel classes in hierarchy numbering higher to keep scope for future additions in  between. 
*/
export enum TravelClassHierarchy {
    Unknown = <any> 'UNKNOWN',
    Standard = <any> 'STANDARD',
    Coach = <any> 'COACH',
    StandardPremium = <any> 'STANDARD_PREMIUM',
    Business = <any> 'BUSINESS',
    BusinessPremium = <any> 'BUSINESS_PREMIUM',
    First = <any> 'FIRST',
    Sleeper = <any> 'SLEEPER'
}
