/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TripPartnerInfo } from './tripPartnerInfo';

/**
* Partner info such as budget info for a given trip Id.
*/
export class TripPartnerInfoResponse {
    /**
    * Spotnana trip Id
    */
    'tripId': string;
    'partnerInfo': TripPartnerInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tripId",
            "baseName": "tripId",
            "type": "string"
        },
        {
            "name": "partnerInfo",
            "baseName": "partnerInfo",
            "type": "TripPartnerInfo"
        }    ];

    static getAttributeTypeMap() {
        return TripPartnerInfoResponse.attributeTypeMap;
    }
}

