/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BasicTripInfo } from './basicTripInfo';
import { PnrBookingStatus } from './pnrBookingStatus';
import { PnrDetailsResponseWithId } from './pnrDetailsResponseWithId';
import { SimplePnr } from './simplePnr';
import { TravelerEventSummary } from './travelerEventSummary';
import { TripAdditionalInfo } from './tripAdditionalInfo';
import { UserFacingStatus } from './userFacingStatus';

/**
* Trip Details Response for a given trip Id
*/
export class TripV3DetailsResponse {
    'basicTripInfo': BasicTripInfo;
    'pnrs': Array<PnrDetailsResponseWithId>;
    'pendingShellPnrs'?: Array<PnrDetailsResponseWithId>;
    'pendingManualFormPnrs'?: Array<PnrDetailsResponseWithId>;
    'tripStatus'?: PnrBookingStatus;
    'tripBookingStatus'?: UserFacingStatus;
    'eventSummary'?: TravelerEventSummary;
    'simplePnrs'?: Array<SimplePnr>;
    'additionalInfo'?: TripAdditionalInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "basicTripInfo",
            "baseName": "basicTripInfo",
            "type": "BasicTripInfo"
        },
        {
            "name": "pnrs",
            "baseName": "pnrs",
            "type": "Array<PnrDetailsResponseWithId>"
        },
        {
            "name": "pendingShellPnrs",
            "baseName": "pendingShellPnrs",
            "type": "Array<PnrDetailsResponseWithId>"
        },
        {
            "name": "pendingManualFormPnrs",
            "baseName": "pendingManualFormPnrs",
            "type": "Array<PnrDetailsResponseWithId>"
        },
        {
            "name": "tripStatus",
            "baseName": "tripStatus",
            "type": "PnrBookingStatus"
        },
        {
            "name": "tripBookingStatus",
            "baseName": "tripBookingStatus",
            "type": "UserFacingStatus"
        },
        {
            "name": "eventSummary",
            "baseName": "eventSummary",
            "type": "TravelerEventSummary"
        },
        {
            "name": "simplePnrs",
            "baseName": "simplePnrs",
            "type": "Array<SimplePnr>"
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "TripAdditionalInfo"
        }    ];

    static getAttributeTypeMap() {
        return TripV3DetailsResponse.attributeTypeMap;
    }
}

export namespace TripV3DetailsResponse {
}
