/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Card } from './card';
import { SimpleMoney } from './simpleMoney';

/**
* Trip budget Info
*/
export class TripBudgetInfo {
    /**
    * Name of the budget
    */
    'budgetName': string;
    /**
    * Remaining balance of the budget. It will be present only if the user has role agent and  above. 
    */
    'budgetRemainingBalance'?: SimpleMoney;
    /**
    * Whether the personal card is allowed for the trip.
    */
    'isPersonalCardAllowed'?: boolean = false;
    /**
    * Whether the budget is masked.
    */
    'isBudgetMasked'?: boolean = false;
    /**
    * Remaining balance of the budget in formatted string.
    */
    'budgetRemainingBalanceFormatted'?: string;
    /**
    * Details of the external card.
    */
    'externalCardDetails'?: Card;
    /**
    * Whether the reward points are allowed on the budget.
    */
    'isRewardPointsAllowed'?: boolean = false;
    /**
    * Available reward point balance.
    */
    'rewardPoints'?: number;
    /**
    * Available reward points value in USD.
    */
    'rewardPointsValueUsd'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "budgetName",
            "baseName": "budgetName",
            "type": "string"
        },
        {
            "name": "budgetRemainingBalance",
            "baseName": "budgetRemainingBalance",
            "type": "SimpleMoney"
        },
        {
            "name": "isPersonalCardAllowed",
            "baseName": "isPersonalCardAllowed",
            "type": "boolean"
        },
        {
            "name": "isBudgetMasked",
            "baseName": "isBudgetMasked",
            "type": "boolean"
        },
        {
            "name": "budgetRemainingBalanceFormatted",
            "baseName": "budgetRemainingBalanceFormatted",
            "type": "string"
        },
        {
            "name": "externalCardDetails",
            "baseName": "externalCardDetails",
            "type": "Card"
        },
        {
            "name": "isRewardPointsAllowed",
            "baseName": "isRewardPointsAllowed",
            "type": "boolean"
        },
        {
            "name": "rewardPoints",
            "baseName": "rewardPoints",
            "type": "number"
        },
        {
            "name": "rewardPointsValueUsd",
            "baseName": "rewardPointsValueUsd",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TripBudgetInfo.attributeTypeMap;
    }
}

