/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Image } from './image';
import { Name } from './name';
import { Persona } from './persona';
import { PhoneNumber } from './phoneNumber';
import { Tier } from './tier';
import { UserOrgId } from './userOrgId';

/**
* Basic user information.
*/
export class UserBasicInfo {
    'userOrgId'?: UserOrgId;
    'persona'?: Persona;
    'email'?: string;
    'name'?: Name;
    'profilePicture'?: Image;
    'tier'?: Tier;
    'phoneNumber'?: PhoneNumber;
    /**
    * Employee id of the user
    */
    'employeeId'?: string;
    /**
    * Whether user profile is active or not.
    */
    'isActive'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userOrgId",
            "baseName": "userOrgId",
            "type": "UserOrgId"
        },
        {
            "name": "persona",
            "baseName": "persona",
            "type": "Persona"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Name"
        },
        {
            "name": "profilePicture",
            "baseName": "profilePicture",
            "type": "Image"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "Tier"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "PhoneNumber"
        },
        {
            "name": "employeeId",
            "baseName": "employeeId",
            "type": "string"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UserBasicInfo.attributeTypeMap;
    }
}

export namespace UserBasicInfo {
}
