/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* User facing booking status
*/
export enum UserFacingStatus {
    UnknownStatus = <any> 'UNKNOWN_STATUS',
    PendingStatus = <any> 'PENDING_STATUS',
    ConfirmedStatus = <any> 'CONFIRMED_STATUS',
    ActiveStatus = <any> 'ACTIVE_STATUS',
    CompletedStatus = <any> 'COMPLETED_STATUS',
    CancelledStatus = <any> 'CANCELLED_STATUS',
    RefundedStatus = <any> 'REFUNDED_STATUS',
    VoidedStatus = <any> 'VOIDED_STATUS',
    ProcessingStatus = <any> 'PROCESSING_STATUS',
    UnconfirmedStatus = <any> 'UNCONFIRMED_STATUS',
    AirlineControlStatus = <any> 'AIRLINE_CONTROL_STATUS',
    PaymentDeclinedStatus = <any> 'PAYMENT_DECLINED_STATUS',
    ScheduleChangeStatus = <any> 'SCHEDULE_CHANGE_STATUS',
    HoldStatus = <any> 'HOLD_STATUS',
    ApprovalRequestedStatus = <any> 'APPROVAL_REQUESTED_STATUS',
    ApprovalDeniedStatus = <any> 'APPROVAL_DENIED_STATUS',
    CancellationInProgressStatus = <any> 'CANCELLATION_IN_PROGRESS_STATUS',
    InoperativeStatus = <any> 'INOPERATIVE_STATUS',
    FlightUnconfirmedStatus = <any> 'FLIGHT_UNCONFIRMED_STATUS'
}
