/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrganizationAgencyId } from './organizationAgencyId';
import { OrganizationId } from './organizationId';
import { TmcBasicInfo } from './tmcBasicInfo';
import { TmcInfo } from './tmcInfo';
import { UserId } from './userId';

/**
* User and user\'s organization information.
*/
export class UserOrgId {
    'organizationAgencyId'?: OrganizationAgencyId;
    'organizationId': OrganizationId;
    'userId': UserId;
    'tmcInfo'?: TmcInfo;
    'tmcBasicInfo'?: TmcBasicInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "organizationAgencyId",
            "baseName": "organizationAgencyId",
            "type": "OrganizationAgencyId"
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "OrganizationId"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserId"
        },
        {
            "name": "tmcInfo",
            "baseName": "tmcInfo",
            "type": "TmcInfo"
        },
        {
            "name": "tmcBasicInfo",
            "baseName": "tmcBasicInfo",
            "type": "TmcBasicInfo"
        }    ];

    static getAttributeTypeMap() {
        return UserOrgId.attributeTypeMap;
    }
}

