/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CostCenter } from './costCenter';
import { Department } from './department';
import { Grade } from './grade';
import { LegalEntityId } from './legalEntityId';
import { Office } from './office';
import { OrganizationId } from './organizationId';
import { PhoneNumber } from './phoneNumber';
import { UserBasicInfo } from './userBasicInfo';
import { UserId } from './userId';

/**
* User business information.
*/
export class UserBusinessInfo {
    'department'?: Department;
    'designation'?: string;
    'email': string;
    /**
    * Unique employee id. Can use email if a company don\'t use employee ids.
    */
    'employeeId': string;
    'grade'?: Grade;
    'legalEntityId': LegalEntityId;
    'managerBasicInfo'?: UserBasicInfo;
    'office'?: Office;
    'organizationId': OrganizationId;
    'phoneNumbers'?: Array<PhoneNumber>;
    'userCostCenter'?: CostCenter;
    /**
    * A list of user basic info for designated approvers.
    */
    'designatedApproverInfos'?: Array<UserBasicInfo>;
    /**
    * A list of userId for designated approvers.
    */
    'designatedApproverUserIds'?: Array<UserId>;
    /**
    * Email address to be used as approval authorizer, when a manager is not present.
    */
    'authorizerEmail'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "department",
            "baseName": "department",
            "type": "Department"
        },
        {
            "name": "designation",
            "baseName": "designation",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "employeeId",
            "baseName": "employeeId",
            "type": "string"
        },
        {
            "name": "grade",
            "baseName": "grade",
            "type": "Grade"
        },
        {
            "name": "legalEntityId",
            "baseName": "legalEntityId",
            "type": "LegalEntityId"
        },
        {
            "name": "managerBasicInfo",
            "baseName": "managerBasicInfo",
            "type": "UserBasicInfo"
        },
        {
            "name": "office",
            "baseName": "office",
            "type": "Office"
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "OrganizationId"
        },
        {
            "name": "phoneNumbers",
            "baseName": "phoneNumbers",
            "type": "Array<PhoneNumber>"
        },
        {
            "name": "userCostCenter",
            "baseName": "userCostCenter",
            "type": "CostCenter"
        },
        {
            "name": "designatedApproverInfos",
            "baseName": "designatedApproverInfos",
            "type": "Array<UserBasicInfo>"
        },
        {
            "name": "designatedApproverUserIds",
            "baseName": "designatedApproverUserIds",
            "type": "Array<UserId>"
        },
        {
            "name": "authorizerEmail",
            "baseName": "authorizerEmail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserBusinessInfo.attributeTypeMap;
    }
}

