/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VendorInfo } from './vendorInfo';
import { VendorProgramPaymentMetadata } from './vendorProgramPaymentMetadata';

/**
* Descriptor for vendor program payment.
*/
export class VendorProgramPaymentDescriptor {
    'vendorInfo'?: VendorInfo;
    'vendorProgramPaymentMetadata': VendorProgramPaymentMetadata;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vendorInfo",
            "baseName": "vendorInfo",
            "type": "VendorInfo"
        },
        {
            "name": "vendorProgramPaymentMetadata",
            "baseName": "vendorProgramPaymentMetadata",
            "type": "VendorProgramPaymentMetadata"
        }    ];

    static getAttributeTypeMap() {
        return VendorProgramPaymentDescriptor.attributeTypeMap;
    }
}

