/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PhoneNumber } from './phoneNumber';

/**
* Car vendor.
*/
export class Vendor {
    /**
    * Vendor code.
    */
    'code': string;
    /**
    * Vendor name.
    */
    'name': string;
    /**
    * Vendor email.
    */
    'email'?: string;
    /**
    * Vendor contact number.
    */
    'phone'?: PhoneNumber;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "PhoneNumber"
        }    ];

    static getAttributeTypeMap() {
        return Vendor.attributeTypeMap;
    }
}

