/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirlineProgram } from './airlineProgram';
import { AirlineProgramWrapper } from './airlineProgramWrapper';
import { DirectBilling } from './directBilling';
import { DirectBillingWrapper } from './directBillingWrapper';

/**
* Vendor program payment specific metadata.
*/
export class VendorProgramPaymentMetadata {
    'directBilling'?: DirectBilling;
    'airlineProgram'?: AirlineProgram;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "directBilling",
            "baseName": "directBilling",
            "type": "DirectBilling"
        },
        {
            "name": "airlineProgram",
            "baseName": "airlineProgram",
            "type": "AirlineProgram"
        }    ];

    static getAttributeTypeMap() {
        return VendorProgramPaymentMetadata.attributeTypeMap;
    }
}

