/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Name/ID etc. of the vendor.
*/
export class VendorInfo {
    /**
    * ID of the vendor.
    */
    'vendorId': string;
    /**
    * Name of the vendor.
    */
    'vendorName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vendorId",
            "baseName": "vendorId",
            "type": "string"
        },
        {
            "name": "vendorName",
            "baseName": "vendorName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return VendorInfo.attributeTypeMap;
    }
}

