/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DirectBilling2 } from './directBilling2';
import { DirectBillingWrapper2 } from './directBillingWrapper2';

/**
* Metadata related to vendor program payment method
*/
export class VendorProgramPaymentMetadata2 {
    'directBilling': DirectBilling2;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "directBilling",
            "baseName": "directBilling",
            "type": "DirectBilling2"
        }    ];

    static getAttributeTypeMap() {
        return VendorProgramPaymentMetadata2.attributeTypeMap;
    }
}

