/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateRange } from './dateRange';
import { Money } from './money';

/**
* Virtual card information like maximum deployment amount, valid date range.
*/
export class VirtualCardInfo {
    /**
    * Virtual card deployment amount. This amount will drive the maximum authorisation value permitted on the virtual card.
    */
    'amount'?: Money;
    /**
    * Date range within which the virtual card can be charged.
    */
    'dateRange'?: DateRange;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "dateRange",
            "baseName": "dateRange",
            "type": "DateRange"
        }    ];

    static getAttributeTypeMap() {
        return VirtualCardInfo.attributeTypeMap;
    }
}

