/**
 * Trip API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of worker.
*/
export enum WorkerType {
    Employee = <any> 'EMPLOYEE',
    Contingent = <any> 'CONTINGENT',
    Seasonal = <any> 'SEASONAL',
    Intern = <any> 'INTERN'
}
